import {
  mdiAlertCircleOutline,
  mdiApps,
  mdiArrowDown,
  mdiArrowUp,
  mdiCalendarCheckOutline,
  mdiCashCheck,
  mdiCashClock,
  mdiCashRemove,
  mdiCashSync,
  mdiChartBoxOutline,
  mdiChartDonutVariant,
  mdiChartTimelineVariant,
  mdiChevronDown,
  mdiChevronLeft,
  mdiChevronRight,
  mdiChevronUp,
  mdiClockCheckOutline,
  mdiClose,
  mdiCloseCircle,
  mdiCoffeeOutline,
  mdiDatabaseOffOutline,
  mdiFlaskOutline,
  mdiInformationOutline,
  mdiMagnify,
  mdiMapClockOutline,
  mdiMenuDown,
  mdiPageFirst,
  mdiPageLast,
  mdiRadar,
  mdiTableEye,
  mdiThemeLightDark,
} from '@mdi/js'

export const vuetifyIconAliases = {
  clear: mdiCloseCircle,
  close: mdiClose,
  collapse: mdiChevronUp,
  dropdown: mdiMenuDown,
  error: mdiCloseCircle,
  expand: mdiChevronDown,
  first: mdiPageFirst,
  last: mdiPageLast,
  next: mdiChevronRight,
  prev: mdiChevronLeft,
  sortAsc: mdiArrowUp,
  sortDesc: mdiArrowDown,
}

export const reportIcons = {
  activeDays: mdiCalendarCheckOutline,
  activeTime: mdiClockCheckOutline,
  aiCostAvailable: mdiCashCheck,
  aiCostEstimated: mdiCashSync,
  aiCostPartial: mdiCashClock,
  aiCostUnavailable: mdiCashRemove,
  aiUsage: mdiChartDonutVariant,
  applications: mdiApps,
  coverage: mdiRadar,
  dailyAverage: mdiChartTimelineVariant,
  databaseUnavailable: mdiDatabaseOffOutline,
  developmentFixture: mdiFlaskOutline,
  emptyChart: mdiChartBoxOutline,
  error: mdiAlertCircleOutline,
  idleTime: mdiCoffeeOutline,
  information: mdiInformationOutline,
  search: mdiMagnify,
  table: mdiTableEye,
  theme: mdiThemeLightDark,
  timeZone: mdiMapClockOutline,
} as const
