using System.Collections.Generic;
using System.Globalization;

namespace TrackMeUp.Services;

/// <summary>
/// Localizes UI labels for supported locales.
/// </summary>
public sealed class LocalizationService
{
    private readonly Dictionary<string, Dictionary<string, string>> _dictionary = new()
    {
        ["en"] = new()
        {
            ["StateRunning"] = "RUNNING",
            ["StatePaused"] = "PAUSED",
            ["StateIdleContext"] = "Idle",
            ["StateReady"] = "Ready to track",
            ["NoSession"] = "No session recorded",
            ["ApiKeyMissing"] = "Insert your API key first.",
            ["ApiKeySaved"] = "Available to TrackMeUp through your Windows user settings. TrackMeUp does not save a copy.",
            ["ContextPlaceholder"] = "Ready to measure your time",
            ["OptionsSaved"] = "Options saved on this PC.",
            ["ReportCreated"] = "Report created",
            ["MenuTitleOptions"] = "App options",
            ["MenuTitleAbout"] = "About",
            ["MenuToggleOpenAi"] = "OpenAI integration",
            ["MenuToggleScreenshot"] = "Take screenshot",
            ["TrackingNoticeRunning"] = "TrackMeUp running...",
            ["TrackingNoticePaused"] = "TrackMeUp paused",
            ["TrackingActionStart"] = "Start tracking",
            ["TrackingActionPause"] = "Pause tracking",
            ["ScreenshotDisabledHint"] = "Screen captures are off",
            ["ScreenshotUnavailableHint"] = "No screen capture available yet",
            ["Snapshot.Delete"] = "Delete snapshot",
            ["LastSessionTitle"] = "LAST SESSION",
            ["ActiveLabel"] = "ACTIVE",
            ["KeysLabel"] = "KEYS",
            ["ClicksLabel"] = "CLICKS",
            ["Main.Menu.Reports"] = "Reports",
            ["Main.Menu.WaybackMachine"] = "Wayback Machine",
            ["Main.Menu.Operations"] = "Tools and diagnostics",
            ["Main.Menu.TakeSnapshotNow"] = "Capture screen now",
            ["Screenshots.Title"] = "Screenshot Inspector",
            ["Screenshots.Caption"] = "Captured moments",
            ["Screenshots.Date.Header"] = "Date",
            ["Screenshots.Date"] = "Screenshot date",
            ["Screenshots.Date.Placeholder"] = "Select a day",
            ["Screenshots.Empty"] = "No screenshots for this day.",
            ["Screenshots.Metadata"] = "Capture details",
            ["Screenshots.DateLabel"] = "Date",
            ["Screenshots.TimeLabel"] = "Time",
            ["Screenshots.ApplicationLabel"] = "Foreground app",
            ["Screenshots.OriginLabel"] = "Origin",
            ["Screenshots.Origin.Manual"] = "Manual",
            ["Screenshots.Origin.Scheduled"] = "Scheduled",
            ["Screenshots.Timeline"] = "Timeline",
            ["Screenshots.Menu.Save"] = "Save selected image",
            ["Screenshots.Menu.OpenFolder"] = "Open containing folder",
            ["Screenshots.Menu.Share"] = "Share with another app",
            ["Screenshots.Menu.DeleteScreenshot"] = "Delete screenshot",
            ["Screenshots.Menu.DeleteSnapshot"] = "Delete snapshot",
            ["Screenshots.Action.Saved"] = "Screenshot saved.",
            ["Screenshots.Action.ShareOpened"] = "Windows sharing is ready.",
            ["Screenshots.Action.FolderOpened"] = "Screenshot folder opened.",
            ["Screenshots.Action.ScreenshotDeleted"] = "Screenshot deleted.",
            ["Screenshots.Action.SnapshotDeleted"] = "Snapshot data deleted.",
            ["Screenshots.Action.Failed"] = "The requested action could not be completed.",
            ["Options.Title"] = "App options",
            ["Options.Subtitle"] = "Local by default. You choose what can leave this PC.",
            ["Options.AiConfiguration.Title"] = "AI configuration",
            ["Options.AiConfiguration.Subtitle"] = "Model, key and thinking effort",
            ["Options.AiConnection"] = "Connection",
            ["Options.AiKeyStorageHint"] = "Stored only in your Windows user environment.",
            ["Options.Advanced"] = "Advanced options",
            ["Options.OpenFolderError"] = "The screen-capture folder could not be opened.",
            ["Options.OpenFolderAction"] = "Open screen-capture folder",
            ["Options.Theme.Header"] = "Theme",
            ["Options.Theme.system"] = "System",
            ["Options.Theme.light"] = "Light",
            ["Options.Theme.dark"] = "Dark",
            ["Options.Position.Header"] = "Player position",
            ["Options.Position.bottom-center"] = "Bottom center",
            ["Options.Position.bottom-left"] = "Bottom left",
            ["Options.Position.bottom-right"] = "Bottom right",
            ["Options.Position.top-left"] = "Top left",
            ["Options.Position.top-right"] = "Top right",
            ["Options.TaskbarPosition.Header"] = "Taskbar control position",
            ["Options.TaskbarPosition.left"] = "Left",
            ["Options.TaskbarPosition.center"] = "Center",
            ["Options.TaskbarPosition.right"] = "Right",
            ["Options.Language.Header"] = "Interface language",
            ["Options.Language.system"] = "System",
            ["Options.Language.en"] = "English",
            ["Options.Language.it"] = "Italiano",
            ["Options.Language.fr"] = "Français",
            ["Options.Language.de"] = "Deutsch",
            ["Options.Language.es"] = "Español",
            ["Options.Language.vi"] = "Tiếng Việt",
            ["Options.Section.Startup"] = "Startup",
            ["Options.Section.Startup.Description"] = "Choose how TrackMeUp behaves after Windows sign-in.",
            ["Options.StartWithWindows.Header"] = "Start with Windows",
            ["Options.StartWithWindows.Off"] = "Off",
            ["Options.StartWithWindows.On"] = "On",
            ["Options.StartTracking.Header"] = "Start tracking on launch",
            ["Options.StartTracking.Off"] = "Wait for Play",
            ["Options.StartTracking.On"] = "Start immediately",
            ["Options.Section.Snapshots"] = "Screen captures",
            ["Options.Section.Snapshots.Description"] = "Choose when screen captures are made and how long they stay here.",
            ["Options.SnapshotsEnabled.Header"] = "Allow screen captures",
            ["Options.SnapshotsEnabled.Off"] = "Off",
            ["Options.SnapshotsEnabled.On"] = "On",
            ["Options.SnapshotFolder.Header"] = "Screen-capture folder",
            ["Options.SnapshotFolder.Placeholder"] = "Folder for screen captures",
            ["Options.SnapshotMode.Header"] = "What to capture",
            ["Options.SnapshotMode.all-screens"] = "All displays",
            ["Options.SnapshotMode.active-window"] = "Active window",
            ["Options.SnapshotResult.Header"] = "Result",
            ["Options.KeepSnapshots.Header"] = "Keep screen captures",
            ["Options.KeepSnapshots.Off"] = "Delete after analysis",
            ["Options.KeepSnapshots.On"] = "Keep on this PC",
            ["Options.Watermark.Header"] = "Screen-capture label",
            ["Options.Watermark.Off"] = "None",
            ["Options.Watermark.On"] = "Add host, date and ID",
            ["Options.Section.Ai"] = "AI",
            ["Options.Section.Ai.Description"] = "Ask an AI service to describe your current context. You can turn it off completely.",
            ["Options.OpenAi.Header"] = "OpenAI integration",
            ["Options.OpenAi.Off"] = "Off",
            ["Options.OpenAi.On"] = "On",
            ["Options.AiProvider.Header"] = "AI service",
            ["Options.AiEndpoint.Header"] = "Service address",
            ["Options.AiKeyVariable.Header"] = "Windows key name",
            ["Options.ApiKey.Header"] = "API key",
            ["Options.ApiKey.Placeholder"] = "Used from Windows; not copied by TrackMeUp",
            ["Options.Model.Header"] = "Model",
            ["Options.OutputDetail.Header"] = "Analysis detail",
            ["Options.OutputDetail.compact"] = "Compact · lowest usage",
            ["Options.OutputDetail.balanced"] = "Balanced",
            ["Options.OutputDetail.detailed"] = "Detailed · larger budget",
            ["Options.Reasoning.Header"] = "Thinking effort",
            ["Options.Reasoning.auto"] = "Automatic",
            ["Options.Reasoning.none"] = "None",
            ["Options.Reasoning.low"] = "Low",
            ["Options.Reasoning.medium"] = "Medium",
            ["Options.Reasoning.high"] = "High",
            ["Options.Reasoning.xhigh"] = "Very high",
            ["Options.Reasoning.max"] = "Maximum",
            ["Options.ModelPreview"] = "Preview",
            ["Options.ModelCatalogError"] = "The AI model catalog could not be loaded.",
            ["Options.ModelRequired"] = "Choose a model.",
            ["Options.ModelUnsupported"] = "The saved model is not available in this catalog.",
            ["Options.ModelImageUnsupported"] = "This text-only preview cannot analyze screen captures.",
            ["Options.ModelImageInput"] = "Image input",
            ["Options.ModelTextOnly"] = "Text only",
            ["Options.ThinkingEffortUnsupported"] = "Choose a thinking effort supported by this model.",
            ["Options.CustomPrompt.Header"] = "Additional AI instruction (optional)",
            ["Options.CustomPrompt.Placeholder"] = "Example: Prioritize concise, factual descriptions.",
            ["Options.DeviceLocation.Header"] = "Include Windows location in AI requests",
            ["Options.DeviceLocation.Off"] = "Off",
            ["Options.DeviceLocation.On"] = "Windows Location",
            ["Options.SaveApiKey"] = "Set key for this PC",
            ["Options.ExportReport"] = "Export HTML report",
            ["Options.Save"] = "Save options",
            ["Options.SaveError"] = "Review the highlighted options and try again.",
            ["Options.ApiKeyError"] = "The API key could not be stored.",
            ["Options.ReportError"] = "The report could not be created.",
            ["Options.SnapshotHintAll"] = "All displays → one screen capture per monitor",
            ["Options.SnapshotHintActive"] = "Active window → one screen capture",
            ["Operations.Title"] = "Tools and status",
            ["Operations.Subtitle"] = "See what TrackMeUp is doing and manage it in one place.",
            ["Operations.Runtime"] = "App and PC",
            ["Operations.Runtime.Description"] = "Check the app and see a current snapshot of your PC.",
            ["Operations.Health"] = "App status",
            ["Operations.SystemSnapshot"] = "PC snapshot",
            ["Operations.SnapshotAi"] = "Screen captures and AI",
            ["Operations.SnapshotAi.Description"] = "Capture the screen or ask AI to describe the current context.",
            ["Operations.TakeSnapshotNow"] = "Capture screen now",
            ["Operations.LatestSnapshot"] = "Latest screen capture",
            ["Operations.OpenFolder"] = "Open folder",
            ["Operations.Analyze"] = "Describe current context",
            ["Operations.Focus"] = "Focus time",
            ["Operations.Focus.Description"] = "Start, check, or stop a focused block of time.",
            ["Operations.FocusObjective.Header"] = "Objective",
            ["Operations.FocusObjective.Placeholder"] = "For example: finish the review",
            ["Operations.Start"] = "Start",
            ["Operations.Status"] = "Status",
            ["Operations.Stop"] = "Stop",
            ["Operations.Summarize"] = "Generate a summary when stopping",
            ["Operations.Reports"] = "Reports",
            ["Operations.Reports.Description"] = "Create reports from the data kept on this PC.",
            ["Operations.OpenGenerated"] = "Open the report after generation",
            ["Operations.TodayReport"] = "Generate today's report",
            ["Operations.DigestDate.Header"] = "Digest date",
            ["Operations.DigestDate.Placeholder"] = "Select a date",
            ["Operations.GenerateDigest"] = "Generate digest",
            ["Operations.Privacy"] = "Privacy",
            ["Operations.Privacy.Description"] = "Tell TrackMeUp which apps or windows to skip.",
            ["Operations.PrivacyType.Header"] = "Skip by",
            ["Operations.PrivacyType.process"] = "App",
            ["Operations.PrivacyType.title"] = "Window title",
            ["Operations.PrivacyType.hint"] = "Context",
            ["Operations.PrivacyValue.Header"] = "Value",
            ["Operations.PrivacyValue.Placeholder"] = "Value to block",
            ["Operations.Add"] = "Add",
            ["Operations.Refresh"] = "Refresh",
            ["Operations.Remove"] = "Remove selected",
            ["Operations.TestContext"] = "Test context",
            ["Operations.Retention"] = "Keep or delete data",
            ["Operations.Retention.Description"] = "See what will be deleted before you confirm.",
            ["Operations.Preview"] = "Preview",
            ["Operations.Run"] = "Run",
            ["Operations.Plugins"] = "Extra app details",
            ["Operations.Plugins.Description"] = "Choose which apps may add useful context.",
            ["Operations.Enable"] = "Enable",
            ["Operations.Disable"] = "Disable",
            ["Operations.Keep"] = "Keep",
            ["Operations.Watermark"] = "Watermark",
            ["Operations.AllowCapture"] = "Allow a new screen capture for this action",
            ["Operations.Initial.Health"] = "App status is not available yet.",
            ["Operations.Initial.SystemSnapshot"] = "PC information is not available yet.",
            ["Operations.Initial.Snapshot"] = "No screen capture yet.",
            ["Operations.Initial.Analysis"] = "No AI description yet.",
            ["Operations.Initial.Focus"] = "No focus block is active.",
            ["Operations.Initial.Report"] = "No report generated.",
            ["Operations.Initial.Retention"] = "Keep/delete settings are not available yet.",
            ["Operations.Initial.RetentionPreview"] = "Preview not calculated yet.",
            ["About.Description"] = "Simple desktop activity tracking that respects your privacy.",
            ["About.Close"] = "Close",
            ["About.Version"] = "Version",
            ["About.Built"] = "Built",
            ["About.Machine"] = "Build machine",
            ["About.Commit"] = "Git commit",
            ["About.Dirty"] = "uncommitted changes",
            ["Reports.Title"] = "Reports",
            ["Reports.Motto"] = "See the shape of your workday.",
            ["Reports.Description"] = "See when you worked, what you used, and how your rhythm changed.",
            ["Reports.Range.Header"] = "Range",
            ["Reports.Range.today"] = "Today",
            ["Reports.Range.7"] = "7 days",
            ["Reports.Range.30"] = "30 days",
            ["Reports.Range.90"] = "90 days",
            ["Reports.Range.thisMonth"] = "This month",
            ["Reports.Range.lastMonth"] = "Last month",
            ["Reports.Range.custom"] = "Custom",
            ["Reports.View.Header"] = "View",
            ["Reports.View.calendar"] = "Calendar",
            ["Reports.View.hourOfWeek"] = "Time bands",
            ["Reports.View.trend"] = "Trend",
            ["Reports.View.applications"] = "Applications",
            ["Reports.From.Header"] = "From",
            ["Reports.To.Header"] = "To",
            ["Reports.Refresh"] = "Refresh"
        },
        ["it"] = new()
        {
            ["StateRunning"] = "IN CORSO",
            ["StatePaused"] = "IN PAUSA",
            ["StateIdleContext"] = "Inattivo",
            ["StateReady"] = "Pronto a misurare il tuo tempo",
            ["NoSession"] = "Nessuna sessione registrata",
            ["ApiKeyMissing"] = "Inserisci prima una API key.",
            ["ApiKeySaved"] = "Disponibile a TrackMeUp tramite le impostazioni utente di Windows. TrackMeUp non ne salva una copia.",
            ["ContextPlaceholder"] = "Pronto a misurare il tuo tempo",
            ["OptionsSaved"] = "Opzioni salvate su questo PC.",
            ["ReportCreated"] = "Report creato",
            ["MenuTitleOptions"] = "Opzioni app",
            ["MenuTitleAbout"] = "About",
            ["MenuToggleOpenAi"] = "Integrazione OpenAI",
            ["MenuToggleScreenshot"] = "Cattura screenshot",
            ["TrackingNoticeRunning"] = "TrackMeUp in esecuzione...",
            ["TrackingNoticePaused"] = "TrackMeUp in pausa",
            ["TrackingActionStart"] = "Avvia monitoraggio",
            ["TrackingActionPause"] = "Metti in pausa il monitoraggio",
            ["ScreenshotDisabledHint"] = "Catture schermo disattivate",
            ["ScreenshotUnavailableHint"] = "Nessuna cattura schermo ancora disponibile",
            ["Snapshot.Delete"] = "Elimina snapshot",
            ["LastSessionTitle"] = "ULTIMA SESSIONE",
            ["ActiveLabel"] = "ATTIVO",
            ["KeysLabel"] = "TASTI",
            ["ClicksLabel"] = "CLICK",
            ["Main.Menu.Reports"] = "Report",
            ["Main.Menu.WaybackMachine"] = "Wayback Machine",
            ["Main.Menu.Operations"] = "Strumenti e diagnostica",
            ["Main.Menu.TakeSnapshotNow"] = "Cattura lo schermo",
            ["Screenshots.Title"] = "Ispettore screenshot",
            ["Screenshots.Caption"] = "Momenti catturati",
            ["Screenshots.Date.Header"] = "Data",
            ["Screenshots.Date"] = "Data dello screenshot",
            ["Screenshots.Date.Placeholder"] = "Seleziona un giorno",
            ["Screenshots.Empty"] = "Nessuno screenshot per questa giornata.",
            ["Screenshots.Metadata"] = "Dettagli della cattura",
            ["Screenshots.DateLabel"] = "Data",
            ["Screenshots.TimeLabel"] = "Ora",
            ["Screenshots.ApplicationLabel"] = "App in primo piano",
            ["Screenshots.OriginLabel"] = "Origine",
            ["Screenshots.Origin.Manual"] = "Manuale",
            ["Screenshots.Origin.Scheduled"] = "Pianificata",
            ["Screenshots.Timeline"] = "Sequenza",
            ["Screenshots.Menu.Save"] = "Salva immagine selezionata",
            ["Screenshots.Menu.OpenFolder"] = "Apri la cartella che la contiene",
            ["Screenshots.Menu.Share"] = "Condividi con un'altra app",
            ["Screenshots.Menu.DeleteScreenshot"] = "Elimina screenshot",
            ["Screenshots.Menu.DeleteSnapshot"] = "Elimina snapshot",
            ["Screenshots.Action.Saved"] = "Screenshot salvato.",
            ["Screenshots.Action.ShareOpened"] = "Condivisione Windows pronta.",
            ["Screenshots.Action.FolderOpened"] = "Cartella degli screenshot aperta.",
            ["Screenshots.Action.ScreenshotDeleted"] = "Screenshot eliminato.",
            ["Screenshots.Action.SnapshotDeleted"] = "Dati dello snapshot eliminati.",
            ["Screenshots.Action.Failed"] = "Impossibile completare l'azione richiesta.",
            ["Options.Title"] = "Opzioni app",
            ["Options.Subtitle"] = "Locale per impostazione predefinita. Decidi tu cosa può uscire dal PC.",
            ["Options.AiConfiguration.Title"] = "Configurazione AI",
            ["Options.AiConfiguration.Subtitle"] = "Modello, chiave e intensità di ragionamento",
            ["Options.AiConnection"] = "Connessione",
            ["Options.AiKeyStorageHint"] = "Salvata solo nell'ambiente utente di Windows.",
            ["Options.Advanced"] = "Opzioni avanzate",
            ["Options.OpenFolderError"] = "Impossibile aprire la cartella delle catture.",
            ["Options.OpenFolderAction"] = "Apri cartella delle catture schermo",
            ["Options.Theme.Header"] = "Tema",
            ["Options.Theme.system"] = "Sistema",
            ["Options.Theme.light"] = "Chiaro",
            ["Options.Theme.dark"] = "Scuro",
            ["Options.Position.Header"] = "Posizione player",
            ["Options.Position.bottom-center"] = "Basso centro",
            ["Options.Position.bottom-left"] = "Basso sinistra",
            ["Options.Position.bottom-right"] = "Basso destra",
            ["Options.Position.top-left"] = "Alto sinistra",
            ["Options.Position.top-right"] = "Alto destra",
            ["Options.TaskbarPosition.Header"] = "Posizione controllo taskbar",
            ["Options.TaskbarPosition.left"] = "Sinistra",
            ["Options.TaskbarPosition.center"] = "Centro",
            ["Options.TaskbarPosition.right"] = "Destra",
            ["Options.Language.Header"] = "Lingua interfaccia",
            ["Options.Language.system"] = "Sistema",
            ["Options.Language.en"] = "English",
            ["Options.Language.it"] = "Italiano",
            ["Options.Language.fr"] = "Français",
            ["Options.Language.de"] = "Deutsch",
            ["Options.Language.es"] = "Español",
            ["Options.Language.vi"] = "Tiếng Việt",
            ["Options.Section.Startup"] = "Avvio",
            ["Options.Section.Startup.Description"] = "Scegli come si comporta TrackMeUp dopo l'accesso a Windows.",
            ["Options.StartWithWindows.Header"] = "Avvia con Windows",
            ["Options.StartWithWindows.Off"] = "Disattivato",
            ["Options.StartWithWindows.On"] = "Attivo",
            ["Options.StartTracking.Header"] = "Avvia tracking all'apertura",
            ["Options.StartTracking.Off"] = "Attendi Play",
            ["Options.StartTracking.On"] = "Avvia subito",
            ["Options.Section.Snapshots"] = "Catture schermo",
            ["Options.Section.Snapshots.Description"] = "Decidi quando catturare lo schermo e per quanto tenere le catture.",
            ["Options.SnapshotsEnabled.Header"] = "Consenti catture schermo",
            ["Options.SnapshotsEnabled.Off"] = "Disattivato",
            ["Options.SnapshotsEnabled.On"] = "Attivo",
            ["Options.SnapshotFolder.Header"] = "Cartella catture schermo",
            ["Options.SnapshotFolder.Placeholder"] = "Cartella per le catture",
            ["Options.SnapshotMode.Header"] = "Cosa catturare",
            ["Options.SnapshotMode.all-screens"] = "Tutti gli schermi",
            ["Options.SnapshotMode.active-window"] = "Finestra attiva",
            ["Options.SnapshotResult.Header"] = "Risultato",
            ["Options.KeepSnapshots.Header"] = "Conserva le catture",
            ["Options.KeepSnapshots.Off"] = "Elimina dopo analisi",
            ["Options.KeepSnapshots.On"] = "Conserva su questo PC",
            ["Options.Watermark.Header"] = "Etichetta sulle catture",
            ["Options.Watermark.Off"] = "Nessuna",
            ["Options.Watermark.On"] = "Aggiungi host, data e ID",
            ["Options.Section.Ai"] = "AI",
            ["Options.Section.Ai.Description"] = "Chiedi a un servizio AI di descrivere il contesto. Puoi disattivarlo completamente.",
            ["Options.OpenAi.Header"] = "Integrazione OpenAI",
            ["Options.OpenAi.Off"] = "Disattivata",
            ["Options.OpenAi.On"] = "Attiva",
            ["Options.AiProvider.Header"] = "Servizio AI",
            ["Options.AiEndpoint.Header"] = "Indirizzo del servizio",
            ["Options.AiKeyVariable.Header"] = "Nome della chiave Windows",
            ["Options.ApiKey.Header"] = "Chiave API",
            ["Options.ApiKey.Placeholder"] = "Usata da Windows; TrackMeUp non ne salva una copia",
            ["Options.Model.Header"] = "Modello",
            ["Options.OutputDetail.Header"] = "Dettaglio analisi",
            ["Options.OutputDetail.compact"] = "Compatto · consumo minimo",
            ["Options.OutputDetail.balanced"] = "Bilanciato",
            ["Options.OutputDetail.detailed"] = "Dettagliato · budget maggiore",
            ["Options.Reasoning.Header"] = "Intensità di ragionamento",
            ["Options.Reasoning.auto"] = "Automatico",
            ["Options.Reasoning.none"] = "Nessuno",
            ["Options.Reasoning.low"] = "Basso",
            ["Options.Reasoning.medium"] = "Medio",
            ["Options.Reasoning.high"] = "Alto",
            ["Options.Reasoning.xhigh"] = "Molto alto",
            ["Options.Reasoning.max"] = "Massimo",
            ["Options.ModelPreview"] = "Anteprima",
            ["Options.ModelCatalogError"] = "Impossibile caricare il catalogo dei modelli AI.",
            ["Options.ModelRequired"] = "Scegli un modello.",
            ["Options.ModelUnsupported"] = "Il modello salvato non è disponibile in questo catalogo.",
            ["Options.ModelImageUnsupported"] = "Questa anteprima solo testo non può analizzare le catture schermo.",
            ["Options.ModelImageInput"] = "Input immagini",
            ["Options.ModelTextOnly"] = "Solo testo",
            ["Options.ThinkingEffortUnsupported"] = "Scegli un'intensità di ragionamento supportata dal modello.",
            ["Options.CustomPrompt.Header"] = "Istruzione AI aggiuntiva (opzionale)",
            ["Options.CustomPrompt.Placeholder"] = "Esempio: privilegia descrizioni concise e fattuali.",
            ["Options.DeviceLocation.Header"] = "Includi la posizione Windows nelle richieste AI",
            ["Options.DeviceLocation.Off"] = "Disattivata",
            ["Options.DeviceLocation.On"] = "Posizione Windows",
            ["Options.SaveApiKey"] = "Imposta chiave su questo PC",
            ["Options.ExportReport"] = "Esporta report HTML",
            ["Options.Save"] = "Salva opzioni",
            ["Options.SaveError"] = "Correggi le opzioni indicate e riprova.",
            ["Options.ApiKeyError"] = "Impossibile impostare la API key.",
            ["Options.ReportError"] = "Impossibile creare il report.",
            ["Options.SnapshotHintAll"] = "Tutti i monitor → una cattura per monitor",
            ["Options.SnapshotHintActive"] = "Finestra attiva → una cattura",
            ["Operations.Title"] = "Strumenti e stato",
            ["Operations.Subtitle"] = "Vedi cosa sta facendo TrackMeUp e gestiscilo da qui.",
            ["Operations.Runtime"] = "App e PC",
            ["Operations.Runtime.Description"] = "Controlla l'app e guarda le informazioni attuali del PC.",
            ["Operations.Health"] = "Stato app",
            ["Operations.SystemSnapshot"] = "Dati del PC",
            ["Operations.SnapshotAi"] = "Catture schermo e AI",
            ["Operations.SnapshotAi.Description"] = "Cattura lo schermo o chiedi all'AI di descrivere il contesto.",
            ["Operations.TakeSnapshotNow"] = "Cattura lo schermo",
            ["Operations.LatestSnapshot"] = "Ultima cattura",
            ["Operations.OpenFolder"] = "Apri cartella",
            ["Operations.Analyze"] = "Descrivi il contesto",
            ["Operations.Focus"] = "Tempo di concentrazione",
            ["Operations.Focus.Description"] = "Avvia, controlla o ferma un blocco di concentrazione.",
            ["Operations.FocusObjective.Header"] = "Obiettivo",
            ["Operations.FocusObjective.Placeholder"] = "Ad esempio: completare la revisione",
            ["Operations.Start"] = "Avvia",
            ["Operations.Status"] = "Stato",
            ["Operations.Stop"] = "Ferma",
            ["Operations.Summarize"] = "Genera un riepilogo alla chiusura",
            ["Operations.Reports"] = "Report",
            ["Operations.Reports.Description"] = "Crea report usando i dati conservati su questo PC.",
            ["Operations.OpenGenerated"] = "Apri il report dopo la generazione",
            ["Operations.TodayReport"] = "Genera report di oggi",
            ["Operations.DigestDate.Header"] = "Data digest",
            ["Operations.DigestDate.Placeholder"] = "Seleziona una data",
            ["Operations.GenerateDigest"] = "Genera digest",
            ["Operations.Privacy"] = "Privacy",
            ["Operations.Privacy.Description"] = "Indica quali app o finestre TrackMeUp deve ignorare.",
            ["Operations.PrivacyType.Header"] = "Ignora per",
            ["Operations.PrivacyType.process"] = "App",
            ["Operations.PrivacyType.title"] = "Titolo finestra",
            ["Operations.PrivacyType.hint"] = "Contesto",
            ["Operations.PrivacyValue.Header"] = "Valore",
            ["Operations.PrivacyValue.Placeholder"] = "Valore da bloccare",
            ["Operations.Add"] = "Aggiungi",
            ["Operations.Refresh"] = "Aggiorna",
            ["Operations.Remove"] = "Rimuovi selezionata",
            ["Operations.TestContext"] = "Test contesto",
            ["Operations.Retention"] = "Conserva o elimina dati",
            ["Operations.Retention.Description"] = "Vedi cosa verrà eliminato prima di confermare.",
            ["Operations.Preview"] = "Anteprima",
            ["Operations.Run"] = "Esegui",
            ["Operations.Plugins"] = "Dettagli delle app",
            ["Operations.Plugins.Description"] = "Scegli quali app possono aggiungere contesto utile.",
            ["Operations.Enable"] = "Abilita",
            ["Operations.Disable"] = "Disabilita",
            ["Operations.Keep"] = "Conserva",
            ["Operations.Watermark"] = "Filigrana",
            ["Operations.AllowCapture"] = "Consenti una nuova cattura per questa azione",
            ["Operations.Initial.Health"] = "Stato app non ancora disponibile.",
            ["Operations.Initial.SystemSnapshot"] = "Informazioni del PC non ancora disponibili.",
            ["Operations.Initial.Snapshot"] = "Nessuna cattura schermo.",
            ["Operations.Initial.Analysis"] = "Nessuna descrizione AI.",
            ["Operations.Initial.Focus"] = "Nessun blocco di concentrazione attivo.",
            ["Operations.Initial.Report"] = "Nessun report generato.",
            ["Operations.Initial.Retention"] = "Impostazioni di conservazione non ancora disponibili.",
            ["Operations.Initial.RetentionPreview"] = "Anteprima non ancora calcolata.",
            ["About.Description"] = "Monitoraggio semplice dell'attività desktop, nel rispetto della tua privacy.",
            ["About.Close"] = "Chiudi",
            ["About.Version"] = "Versione",
            ["About.Built"] = "Compilata il",
            ["About.Machine"] = "Macchina di build",
            ["About.Commit"] = "Commit Git",
            ["About.Dirty"] = "modifiche non committate",
            ["Reports.Title"] = "Report",
            ["Reports.Motto"] = "Guarda la forma della tua giornata.",
            ["Reports.Description"] = "Vedi quando hai lavorato, quali app hai usato e come è cambiato il tuo ritmo.",
            ["Reports.Range.Header"] = "Intervallo",
            ["Reports.Range.today"] = "Oggi",
            ["Reports.Range.7"] = "7 giorni",
            ["Reports.Range.30"] = "30 giorni",
            ["Reports.Range.90"] = "90 giorni",
            ["Reports.Range.thisMonth"] = "Questo mese",
            ["Reports.Range.lastMonth"] = "Mese scorso",
            ["Reports.Range.custom"] = "Personalizzato",
            ["Reports.View.Header"] = "Vista",
            ["Reports.View.calendar"] = "Calendario",
            ["Reports.View.hourOfWeek"] = "Fasce orarie",
            ["Reports.View.trend"] = "Andamento",
            ["Reports.View.applications"] = "Applicazioni",
            ["Reports.From.Header"] = "Dal",
            ["Reports.To.Header"] = "Al",
            ["Reports.Refresh"] = "Aggiorna"
        },
        ["fr"] = new()
        {
            ["StateRunning"] = "EN COURS",
            ["StatePaused"] = "EN PAUSE",
            ["StateIdleContext"] = "Inactif",
            ["StateReady"] = "Prêt à mesurer votre temps",
            ["NoSession"] = "Aucune session enregistrée",
            ["ApiKeyMissing"] = "Saisissez d'abord la clé API.",
            ["ApiKeySaved"] = "Clé enregistrée dans l'environnement utilisateur Windows. Non conservée par l'application.",
            ["ContextPlaceholder"] = "Prêt à mesurer votre temps",
            ["OptionsSaved"] = "Options enregistrées sur ce PC.",
            ["ReportCreated"] = "Rapport créé",
            ["MenuTitleOptions"] = "Options",
            ["MenuTitleAbout"] = "À propos",
            ["MenuToggleOpenAi"] = "Intégration OpenAI",
            ["MenuToggleScreenshot"] = "Capturer l'écran",
            ["TrackingNoticeRunning"] = "TrackMeUp est en cours...",
            ["TrackingNoticePaused"] = "TrackMeUp est en pause",
            ["ScreenshotDisabledHint"] = "Captures désactivées",
            ["ScreenshotUnavailableHint"] = "Aucune capture d’écran disponible pour le moment",
            ["Options.OpenFolderAction"] = "Ouvrir le dossier des captures d’écran",
            ["LastSessionTitle"] = "DERNIÈRE SESSION",
            ["ActiveLabel"] = "ACTIF",
            ["KeysLabel"] = "TOUCHES",
            ["ClicksLabel"] = "CLICS"
        },
        ["de"] = new()
        {
            ["StateRunning"] = "IN ESECUZIONE",
            ["StatePaused"] = "IN PAUSA",
            ["StateIdleContext"] = "Inaktiv",
            ["StateReady"] = "Bereit, Ihre Zeit zu messen",
            ["NoSession"] = "Keine Sitzung aufgezeichnet",
            ["ApiKeyMissing"] = "Bitte zuerst den API-Schlüssel eingeben.",
            ["ApiKeySaved"] = "In die Windows-Benutzerumgebung gespeichert. Nicht in der App gespeichert.",
            ["ContextPlaceholder"] = "Bereit, Ihre Zeit zu messen",
            ["OptionsSaved"] = "Optionen auf diesem PC gespeichert.",
            ["ReportCreated"] = "Bericht erstellt",
            ["MenuTitleOptions"] = "App-Einstellungen",
            ["MenuTitleAbout"] = "Über",
            ["MenuToggleOpenAi"] = "OpenAI-Integration",
            ["MenuToggleScreenshot"] = "Bildschirm aufnehmen",
            ["TrackingNoticeRunning"] = "TrackMeUp wird ausgeführt...",
            ["TrackingNoticePaused"] = "TrackMeUp ist pausiert",
            ["ScreenshotDisabledHint"] = "Screenshots deaktiviert",
            ["ScreenshotUnavailableHint"] = "Noch kein Screenshot verfügbar",
            ["Options.OpenFolderAction"] = "Screenshot-Ordner öffnen",
            ["LastSessionTitle"] = "LETZTE SITZUNG",
            ["ActiveLabel"] = "AKTIV",
            ["KeysLabel"] = "TASTEN",
            ["ClicksLabel"] = "KLICKS"
        },
        ["es"] = new()
        {
            ["StateRunning"] = "EN CURSO",
            ["StatePaused"] = "PAUSADO",
            ["StateIdleContext"] = "Inactivo",
            ["StateReady"] = "Listo para medir tu tiempo",
            ["NoSession"] = "No hay sesión registrada",
            ["ApiKeyMissing"] = "Introduce primero una clave API.",
            ["ApiKeySaved"] = "Guardada en entorno de usuario de Windows. No se guarda en la app.",
            ["ContextPlaceholder"] = "Listo para medir tu tiempo",
            ["OptionsSaved"] = "Opciones guardadas en este PC.",
            ["ReportCreated"] = "Informe creado",
            ["MenuTitleOptions"] = "Opciones",
            ["MenuTitleAbout"] = "Acerca de",
            ["MenuToggleOpenAi"] = "Integración OpenAI",
            ["MenuToggleScreenshot"] = "Capturar pantalla",
            ["TrackingNoticeRunning"] = "TrackMeUp se está ejecutando...",
            ["TrackingNoticePaused"] = "TrackMeUp está en pausa",
            ["ScreenshotDisabledHint"] = "Capturas desactivadas",
            ["ScreenshotUnavailableHint"] = "Aún no hay capturas disponibles",
            ["Options.OpenFolderAction"] = "Abrir carpeta de capturas",
            ["LastSessionTitle"] = "ÚLTIMA SESIÓN",
            ["ActiveLabel"] = "ACTIVO",
            ["KeysLabel"] = "TECLAS",
            ["ClicksLabel"] = "CLICS"
        },
        ["vi"] = new()
        {
            ["StateRunning"] = "ĐANG THỰC HIỆN",
            ["StatePaused"] = "TẠM DỪNG",
            ["StateIdleContext"] = "Không hoạt động",
            ["StateReady"] = "Sẵn sàng đo thời gian của bạn",
            ["NoSession"] = "Không có phiên làm việc nào",
            ["ApiKeyMissing"] = "Nhập khóa API trước.",
            ["ApiKeySaved"] = "Lưu vào môi trường người dùng Windows. Không được lưu bởi ứng dụng.",
            ["ContextPlaceholder"] = "Sẵn sàng đo thời gian của bạn",
            ["OptionsSaved"] = "Đã lưu tùy chọn trên PC này.",
            ["ReportCreated"] = "Đã tạo báo cáo",
            ["MenuTitleOptions"] = "Tùy chọn",
            ["MenuTitleAbout"] = "Giới thiệu",
            ["MenuToggleOpenAi"] = "Tích hợp OpenAI",
            ["MenuToggleScreenshot"] = "Chụp màn hình",
            ["TrackingNoticeRunning"] = "TrackMeUp đang chạy...",
            ["TrackingNoticePaused"] = "TrackMeUp đã tạm dừng",
            ["ScreenshotDisabledHint"] = "Ảnh chụp đã tắt",
            ["ScreenshotUnavailableHint"] = "Chưa có ảnh chụp màn hình",
            ["Options.OpenFolderAction"] = "Mở thư mục ảnh chụp màn hình",
            ["LastSessionTitle"] = "PHIÊN LÀM VIỆC CUỐI CÙNG",
            ["ActiveLabel"] = "HOẠT ĐỘNG",
            ["KeysLabel"] = "PHÍM",
            ["ClicksLabel"] = "BẤM"
        }
    };

    /// <summary>
    /// Selected language code.
    /// </summary>
    public string Language { get; }

    /// <summary>Gets the persisted language choice before system-language resolution.</summary>
    public string RequestedLanguage { get; }

    /// <summary>
    /// Creates service for supported language fallback to English.
    /// </summary>
    public LocalizationService(string language)
    {
        RequestedLanguage = string.IsNullOrWhiteSpace(language) ? "system" : language.Trim().ToLowerInvariant();
        Language = ResolveLanguage(RequestedLanguage, CultureInfo.CurrentUICulture);
    }

    /// <summary>Resolves a persisted override, using the Windows UI culture only for the system choice.</summary>
    public static string ResolveLanguage(string? requestedLanguage, CultureInfo systemCulture)
    {
        ArgumentNullException.ThrowIfNull(systemCulture);
        var requested = string.IsNullOrWhiteSpace(requestedLanguage) ? "system" : requestedLanguage.Trim().ToLowerInvariant();
        var resolved = requested == "system" ? systemCulture.TwoLetterISOLanguageName.ToLowerInvariant() : requested;
        return resolved is "en" or "it" or "vi" or "fr" or "de" or "es" ? resolved : "en";
    }

    /// <summary>
    /// Returns translated token text for given key.
    /// </summary>
    /// <param name="key">Resource key.</param>
    /// <returns>Localized value or fallback key.</returns>
    public string Translate(string key)
        => _dictionary.TryGetValue(Language, out var current) && current.TryGetValue(key, out var value)
            ? value
            : _dictionary["en"].TryGetValue(key, out var english)
                ? english
                : key;

    /// <summary>Tries the selected language and then the English product copy fallback.</summary>
    public bool TryTranslate(string key, out string value)
    {
        if (_dictionary.TryGetValue(Language, out var current) && current.TryGetValue(key, out value!))
        {
            return true;
        }

        return _dictionary["en"].TryGetValue(key, out value!);
    }
}
