using System.Collections.Generic;
using System.Globalization;

namespace TrackMeUp.Services;

/// <summary>
/// Localizes UI labels for supported locales.
/// </summary>
public sealed class LocalizationService
{
    private readonly Dictionary<string, Dictionary<string, string>> _dictionary = new()
    {
        ["en"] = new()
        {
            ["StateRunning"] = "RUNNING",
            ["StatePaused"] = "PAUSED",
            ["StateIdleContext"] = "Idle",
            ["StateReady"] = "Ready to track",
            ["NoSession"] = "No session recorded",
            ["ApiKeyMissing"] = "Insert your API key first.",
            ["ApiKeySaved"] = "Stored in Windows user environment only. Not persisted by app.",
            ["ContextPlaceholder"] = "Ready to measure your time",
            ["OptionsSaved"] = "Options saved in local appsettings.json.",
            ["ReportCreated"] = "Report created",
            ["MenuTitleOptions"] = "App options",
            ["MenuTitleAbout"] = "About",
            ["MenuToggleOpenAi"] = "OpenAI integration",
            ["MenuToggleScreenshot"] = "Take snapshot now",
            ["TrackingNoticeRunning"] = "TrackMeUp running...",
            ["TrackingNoticePaused"] = "TrackMeUp paused",
            ["TrackingActionStart"] = "Start tracking",
            ["TrackingActionPause"] = "Pause tracking",
            ["ScreenshotDisabledHint"] = "Snapshots disabled",
            ["LastSessionTitle"] = "LAST SESSION",
            ["ActiveLabel"] = "ACTIVE",
            ["KeysLabel"] = "KEYS",
            ["ClicksLabel"] = "CLICKS",
            ["Main.Menu.Reports"] = "Reports",
            ["Main.Menu.Operations"] = "Tools and diagnostics",
            ["Main.Menu.TakeSnapshotNow"] = "Take snapshot now",
            ["Options.Title"] = "App options",
            ["Options.Subtitle"] = "Your data stays on this PC",
            ["Options.Theme.Header"] = "Theme",
            ["Options.Theme.system"] = "System",
            ["Options.Theme.light"] = "Light",
            ["Options.Theme.dark"] = "Dark",
            ["Options.Position.Header"] = "Player position",
            ["Options.Position.bottom-center"] = "Bottom center",
            ["Options.Position.bottom-left"] = "Bottom left",
            ["Options.Position.bottom-right"] = "Bottom right",
            ["Options.Position.top-left"] = "Top left",
            ["Options.Position.top-right"] = "Top right",
            ["Options.TaskbarPosition.Header"] = "Taskbar control position",
            ["Options.TaskbarPosition.left"] = "Left",
            ["Options.TaskbarPosition.center"] = "Center",
            ["Options.TaskbarPosition.right"] = "Right",
            ["Options.Language.Header"] = "Interface language",
            ["Options.Language.system"] = "System",
            ["Options.Language.en"] = "English",
            ["Options.Language.it"] = "Italiano",
            ["Options.Language.fr"] = "Français",
            ["Options.Language.de"] = "Deutsch",
            ["Options.Language.es"] = "Español",
            ["Options.Language.vi"] = "Tiếng Việt",
            ["Options.Section.Startup"] = "Startup",
            ["Options.Section.Startup.Description"] = "Choose how TrackMeUp behaves after Windows sign-in.",
            ["Options.StartWithWindows.Header"] = "Start with Windows",
            ["Options.StartWithWindows.Off"] = "Off",
            ["Options.StartWithWindows.On"] = "On",
            ["Options.StartTracking.Header"] = "Start tracking on launch",
            ["Options.StartTracking.Off"] = "Wait for Play",
            ["Options.StartTracking.On"] = "Start immediately",
            ["Options.Section.Snapshots"] = "Snapshots",
            ["Options.Section.Snapshots.Description"] = "Control local WebP captures and retention.",
            ["Options.SnapshotsEnabled.Header"] = "Enable snapshots",
            ["Options.SnapshotsEnabled.Off"] = "Off",
            ["Options.SnapshotsEnabled.On"] = "On",
            ["Options.SnapshotFolder.Header"] = "Snapshot folder",
            ["Options.SnapshotFolder.Placeholder"] = "WebP folder",
            ["Options.SnapshotMode.Header"] = "Capture mode",
            ["Options.SnapshotMode.all-screens"] = "All displays",
            ["Options.SnapshotMode.active-window"] = "Active window",
            ["Options.SnapshotResult.Header"] = "Result",
            ["Options.KeepSnapshots.Header"] = "Keep snapshots",
            ["Options.KeepSnapshots.Off"] = "Delete after analysis",
            ["Options.KeepSnapshots.On"] = "Store locally",
            ["Options.Watermark.Header"] = "Snapshot watermark",
            ["Options.Watermark.Off"] = "None",
            ["Options.Watermark.On"] = "Add host, date and ID",
            ["Options.Section.Ai"] = "AI",
            ["Options.Section.Ai.Description"] = "Configure the provider, model and analysis behavior.",
            ["Options.OpenAi.Header"] = "OpenAI integration",
            ["Options.OpenAi.Off"] = "Off",
            ["Options.OpenAi.On"] = "On",
            ["Options.AiProvider.Header"] = "AI provider",
            ["Options.AiEndpoint.Header"] = "Endpoint",
            ["Options.AiKeyVariable.Header"] = "API key variable name",
            ["Options.ApiKey.Header"] = "Temporary API key",
            ["Options.ApiKey.Placeholder"] = "API key (not stored in settings)",
            ["Options.Model.Header"] = "Model",
            ["Options.OutputDetail.Header"] = "Snapshot analysis detail",
            ["Options.OutputDetail.compact"] = "Compact · lowest usage",
            ["Options.OutputDetail.balanced"] = "Balanced",
            ["Options.OutputDetail.detailed"] = "Detailed · larger budget",
            ["Options.Reasoning.Header"] = "Reasoning effort",
            ["Options.Reasoning.auto"] = "Automatic",
            ["Options.Reasoning.none"] = "None",
            ["Options.Reasoning.low"] = "Low",
            ["Options.Reasoning.medium"] = "Medium",
            ["Options.Reasoning.high"] = "High",
            ["Options.Reasoning.xhigh"] = "Very high",
            ["Options.Reasoning.max"] = "Maximum",
            ["Options.CustomPrompt.Header"] = "Additional AI instruction (optional)",
            ["Options.CustomPrompt.Placeholder"] = "Example: Prioritize concise, factual descriptions.",
            ["Options.DeviceLocation.Header"] = "Include device location in AI snapshots",
            ["Options.DeviceLocation.Off"] = "Off",
            ["Options.DeviceLocation.On"] = "Windows Location",
            ["Options.AutomaticAnalysis.Header"] = "Automatic analysis",
            ["Options.AutomaticAnalysis.Off"] = "On demand only",
            ["Options.AutomaticAnalysis.On"] = "Every 15 minutes",
            ["Options.SaveApiKey"] = "Save API key",
            ["Options.Section.ActiveHours"] = "Active hours",
            ["Options.Section.ActiveHours.Description"] = "Informational context for AI snapshots only. Use HH:mm-HH:mm and commas between breaks.",
            ["Options.ActiveHours"] = "Active hours",
            ["Options.Breaks"] = "Breaks",
            ["Options.Day.monday"] = "Monday",
            ["Options.Day.tuesday"] = "Tuesday",
            ["Options.Day.wednesday"] = "Wednesday",
            ["Options.Day.thursday"] = "Thursday",
            ["Options.Day.friday"] = "Friday",
            ["Options.Day.saturday"] = "Saturday",
            ["Options.Day.sunday"] = "Sunday",
            ["Options.ExportReport"] = "Export HTML report",
            ["Options.Save"] = "Save options",
            ["Options.SaveError"] = "Review the highlighted options and try again.",
            ["Options.ApiKeyError"] = "The API key could not be stored.",
            ["Options.ReportError"] = "The report could not be created.",
            ["Options.SnapshotHintAll"] = "All displays → one WebP per monitor",
            ["Options.SnapshotHintActive"] = "Active window → one WebP",
            ["Operations.Title"] = "Tools and diagnostics",
            ["Operations.Subtitle"] = "All operations use the shared app runtime.",
            ["Operations.Runtime"] = "Runtime and system",
            ["Operations.Runtime.Description"] = "Inspect runtime health and capture a current system snapshot.",
            ["Operations.Health"] = "Health",
            ["Operations.SystemSnapshot"] = "System snapshot",
            ["Operations.SnapshotAi"] = "Snapshots and AI analysis",
            ["Operations.SnapshotAi.Description"] = "Capture the current context or request an AI analysis.",
            ["Operations.TakeSnapshotNow"] = "Take snapshot now",
            ["Operations.LatestSnapshot"] = "Latest snapshot",
            ["Operations.OpenFolder"] = "Open folder",
            ["Operations.Analyze"] = "Analyze current context",
            ["Operations.Focus"] = "Focus session",
            ["Operations.Focus.Description"] = "Start, inspect or stop a measured focus session.",
            ["Operations.FocusObjective.Header"] = "Objective",
            ["Operations.FocusObjective.Placeholder"] = "For example: finish the review",
            ["Operations.Start"] = "Start",
            ["Operations.Status"] = "Status",
            ["Operations.Stop"] = "Stop",
            ["Operations.Summarize"] = "Generate a summary when stopping",
            ["Operations.Reports"] = "Reports and digest",
            ["Operations.Reports.Description"] = "Generate local reports from the current data store.",
            ["Operations.OpenGenerated"] = "Open the report after generation",
            ["Operations.TodayReport"] = "Generate today's report",
            ["Operations.DigestDate.Header"] = "Digest date",
            ["Operations.DigestDate.Placeholder"] = "Select a date",
            ["Operations.GenerateDigest"] = "Generate digest",
            ["Operations.Privacy"] = "Privacy",
            ["Operations.Privacy.Description"] = "Block sensitive processes, window titles or context hints.",
            ["Operations.PrivacyType.Header"] = "Rule type",
            ["Operations.PrivacyType.process"] = "Process",
            ["Operations.PrivacyType.title"] = "Window title",
            ["Operations.PrivacyType.hint"] = "Context",
            ["Operations.PrivacyValue.Header"] = "Value",
            ["Operations.PrivacyValue.Placeholder"] = "Value to block",
            ["Operations.Add"] = "Add",
            ["Operations.Refresh"] = "Refresh",
            ["Operations.Remove"] = "Remove selected",
            ["Operations.TestContext"] = "Test context",
            ["Operations.Retention"] = "Data retention",
            ["Operations.Retention.Description"] = "Review the policy before running a confirmed cleanup.",
            ["Operations.Preview"] = "Preview",
            ["Operations.Run"] = "Run",
            ["Operations.Plugins"] = "Context plugins",
            ["Operations.Plugins.Description"] = "Enable or disable supported application context providers.",
            ["Operations.Enable"] = "Enable",
            ["Operations.Disable"] = "Disable",
            ["Operations.Keep"] = "Keep",
            ["Operations.Watermark"] = "Watermark",
            ["Operations.AllowCapture"] = "Allow a new snapshot when required",
            ["Operations.Initial.Health"] = "Health not acquired yet.",
            ["Operations.Initial.SystemSnapshot"] = "System snapshot not acquired yet.",
            ["Operations.Initial.Snapshot"] = "No snapshot captured.",
            ["Operations.Initial.Analysis"] = "No analysis performed.",
            ["Operations.Initial.Focus"] = "No focus session is active.",
            ["Operations.Initial.Report"] = "No report generated.",
            ["Operations.Initial.Retention"] = "Policy not loaded yet.",
            ["Operations.Initial.RetentionPreview"] = "Preview not calculated yet.",
            ["About.Description"] = "A local activity player for understanding time, applications and work rhythm. Typed content is never recorded; snapshots and OpenAI are always opt-in.",
            ["About.Close"] = "Close",
            ["About.Version"] = "Version",
            ["About.Built"] = "Built",
            ["About.Machine"] = "Build machine",
            ["About.Commit"] = "Git commit",
            ["About.Dirty"] = "uncommitted changes",
            ["Reports.Title"] = "Reports",
            ["Reports.Motto"] = "Turn data into rhythm.",
            ["Reports.Description"] = "See when you work, where your time goes and how consistently.",
            ["Reports.Range.Header"] = "Range",
            ["Reports.Range.today"] = "Today",
            ["Reports.Range.7"] = "7 days",
            ["Reports.Range.30"] = "30 days",
            ["Reports.Range.90"] = "90 days",
            ["Reports.Range.thisMonth"] = "This month",
            ["Reports.Range.lastMonth"] = "Last month",
            ["Reports.Range.custom"] = "Custom",
            ["Reports.View.Header"] = "View",
            ["Reports.View.calendar"] = "Calendar",
            ["Reports.View.hourOfWeek"] = "Time bands",
            ["Reports.View.trend"] = "Trend",
            ["Reports.View.applications"] = "Applications",
            ["Reports.From.Header"] = "From",
            ["Reports.To.Header"] = "To",
            ["Reports.Refresh"] = "Refresh"
        },
        ["it"] = new()
        {
            ["StateRunning"] = "IN CORSO",
            ["StatePaused"] = "IN PAUSA",
            ["StateIdleContext"] = "Inattivo",
            ["StateReady"] = "Pronto a misurare il tuo tempo",
            ["NoSession"] = "Nessuna sessione registrata",
            ["ApiKeyMissing"] = "Inserisci prima una API key.",
            ["ApiKeySaved"] = "Impostata nell'ambiente utente Windows. Non viene salvata dall'app.",
            ["ContextPlaceholder"] = "Pronto a misurare il tuo tempo",
            ["OptionsSaved"] = "Opzioni salvate in appsettings.json locale.",
            ["ReportCreated"] = "Report creato",
            ["MenuTitleOptions"] = "Opzioni app",
            ["MenuTitleAbout"] = "About",
            ["MenuToggleOpenAi"] = "OpenAI integration",
            ["MenuToggleScreenshot"] = "Take snapshot now",
            ["TrackingNoticeRunning"] = "TrackMeUp in esecuzione...",
            ["TrackingNoticePaused"] = "TrackMeUp in pausa",
            ["TrackingActionStart"] = "Avvia monitoraggio",
            ["TrackingActionPause"] = "Metti in pausa il monitoraggio",
            ["ScreenshotDisabledHint"] = "Snapshot disattivati",
            ["LastSessionTitle"] = "ULTIMA SESSIONE",
            ["ActiveLabel"] = "ATTIVO",
            ["KeysLabel"] = "TASTI",
            ["ClicksLabel"] = "CLICK",
            ["Main.Menu.Reports"] = "Report",
            ["Main.Menu.Operations"] = "Strumenti e diagnostica",
            ["Main.Menu.TakeSnapshotNow"] = "Take snapshot now",
            ["Options.Title"] = "Opzioni app",
            ["Options.Subtitle"] = "I tuoi dati restano su questo PC",
            ["Options.Theme.Header"] = "Tema",
            ["Options.Theme.system"] = "Sistema",
            ["Options.Theme.light"] = "Chiaro",
            ["Options.Theme.dark"] = "Scuro",
            ["Options.Position.Header"] = "Posizione player",
            ["Options.Position.bottom-center"] = "Basso centro",
            ["Options.Position.bottom-left"] = "Basso sinistra",
            ["Options.Position.bottom-right"] = "Basso destra",
            ["Options.Position.top-left"] = "Alto sinistra",
            ["Options.Position.top-right"] = "Alto destra",
            ["Options.TaskbarPosition.Header"] = "Posizione controllo taskbar",
            ["Options.TaskbarPosition.left"] = "Sinistra",
            ["Options.TaskbarPosition.center"] = "Centro",
            ["Options.TaskbarPosition.right"] = "Destra",
            ["Options.Language.Header"] = "Lingua interfaccia",
            ["Options.Language.system"] = "Sistema",
            ["Options.Language.en"] = "English",
            ["Options.Language.it"] = "Italiano",
            ["Options.Language.fr"] = "Français",
            ["Options.Language.de"] = "Deutsch",
            ["Options.Language.es"] = "Español",
            ["Options.Language.vi"] = "Tiếng Việt",
            ["Options.Section.Startup"] = "Avvio",
            ["Options.Section.Startup.Description"] = "Scegli come si comporta TrackMeUp dopo l'accesso a Windows.",
            ["Options.StartWithWindows.Header"] = "Avvia con Windows",
            ["Options.StartWithWindows.Off"] = "Disattivato",
            ["Options.StartWithWindows.On"] = "Attivo",
            ["Options.StartTracking.Header"] = "Avvia tracking all'apertura",
            ["Options.StartTracking.Off"] = "Attendi Play",
            ["Options.StartTracking.On"] = "Avvia subito",
            ["Options.Section.Snapshots"] = "Snapshot",
            ["Options.Section.Snapshots.Description"] = "Controlla le catture WebP locali e la loro conservazione.",
            ["Options.SnapshotsEnabled.Header"] = "Abilita snapshot",
            ["Options.SnapshotsEnabled.Off"] = "Disattivato",
            ["Options.SnapshotsEnabled.On"] = "Attivo",
            ["Options.SnapshotFolder.Header"] = "Cartella snapshot",
            ["Options.SnapshotFolder.Placeholder"] = "Cartella WebP",
            ["Options.SnapshotMode.Header"] = "Modalità di cattura",
            ["Options.SnapshotMode.all-screens"] = "Tutti gli schermi",
            ["Options.SnapshotMode.active-window"] = "Finestra attiva",
            ["Options.SnapshotResult.Header"] = "Risultato",
            ["Options.KeepSnapshots.Header"] = "Conserva snapshot",
            ["Options.KeepSnapshots.Off"] = "Elimina dopo analisi",
            ["Options.KeepSnapshots.On"] = "Archivia localmente",
            ["Options.Watermark.Header"] = "Filigrana snapshot",
            ["Options.Watermark.Off"] = "Nessuna",
            ["Options.Watermark.On"] = "Aggiungi host, data e ID",
            ["Options.Section.Ai"] = "AI",
            ["Options.Section.Ai.Description"] = "Configura provider, modello e comportamento dell'analisi.",
            ["Options.OpenAi.Header"] = "Integrazione OpenAI",
            ["Options.OpenAi.Off"] = "Disattivata",
            ["Options.OpenAi.On"] = "Attiva",
            ["Options.AiProvider.Header"] = "Provider AI",
            ["Options.AiEndpoint.Header"] = "Endpoint",
            ["Options.AiKeyVariable.Header"] = "Nome variabile API key",
            ["Options.ApiKey.Header"] = "API key temporanea",
            ["Options.ApiKey.Placeholder"] = "API key (non salvata nelle impostazioni)",
            ["Options.Model.Header"] = "Modello",
            ["Options.OutputDetail.Header"] = "Dettaglio analisi snapshot",
            ["Options.OutputDetail.compact"] = "Compatto · consumo minimo",
            ["Options.OutputDetail.balanced"] = "Bilanciato",
            ["Options.OutputDetail.detailed"] = "Dettagliato · budget maggiore",
            ["Options.Reasoning.Header"] = "Livello di ragionamento",
            ["Options.Reasoning.auto"] = "Automatico",
            ["Options.Reasoning.none"] = "Nessuno",
            ["Options.Reasoning.low"] = "Basso",
            ["Options.Reasoning.medium"] = "Medio",
            ["Options.Reasoning.high"] = "Alto",
            ["Options.Reasoning.xhigh"] = "Molto alto",
            ["Options.Reasoning.max"] = "Massimo",
            ["Options.CustomPrompt.Header"] = "Istruzione AI aggiuntiva (opzionale)",
            ["Options.CustomPrompt.Placeholder"] = "Esempio: privilegia descrizioni concise e fattuali.",
            ["Options.DeviceLocation.Header"] = "Includi la posizione nei snapshot AI",
            ["Options.DeviceLocation.Off"] = "Disattivata",
            ["Options.DeviceLocation.On"] = "Posizione Windows",
            ["Options.AutomaticAnalysis.Header"] = "Analisi automatica",
            ["Options.AutomaticAnalysis.Off"] = "Solo su richiesta",
            ["Options.AutomaticAnalysis.On"] = "Ogni 15 minuti",
            ["Options.SaveApiKey"] = "Salva chiave API",
            ["Options.Section.ActiveHours"] = "Orari attivi",
            ["Options.Section.ActiveHours.Description"] = "Solo contesto informativo per gli snapshot AI. Usa HH:mm-HH:mm e separa le pause con virgole.",
            ["Options.ActiveHours"] = "Orari attivi",
            ["Options.Breaks"] = "Pause",
            ["Options.Day.monday"] = "Lunedì",
            ["Options.Day.tuesday"] = "Martedì",
            ["Options.Day.wednesday"] = "Mercoledì",
            ["Options.Day.thursday"] = "Giovedì",
            ["Options.Day.friday"] = "Venerdì",
            ["Options.Day.saturday"] = "Sabato",
            ["Options.Day.sunday"] = "Domenica",
            ["Options.ExportReport"] = "Esporta report HTML",
            ["Options.Save"] = "Salva opzioni",
            ["Options.SaveError"] = "Correggi le opzioni indicate e riprova.",
            ["Options.ApiKeyError"] = "Impossibile impostare la API key.",
            ["Options.ReportError"] = "Impossibile creare il report.",
            ["Options.SnapshotHintAll"] = "Tutti gli schermi → un WebP per monitor",
            ["Options.SnapshotHintActive"] = "Finestra attiva → un WebP",
            ["Operations.Title"] = "Strumenti e diagnostica",
            ["Operations.Subtitle"] = "Tutte le operazioni usano il runtime condiviso dell'app.",
            ["Operations.Runtime"] = "Runtime e sistema",
            ["Operations.Runtime.Description"] = "Controlla lo stato del runtime e acquisisci uno snapshot del sistema.",
            ["Operations.Health"] = "Health",
            ["Operations.SystemSnapshot"] = "Snapshot sistema",
            ["Operations.SnapshotAi"] = "Snapshot e analisi AI",
            ["Operations.SnapshotAi.Description"] = "Cattura il contesto corrente o richiedi un'analisi AI.",
            ["Operations.TakeSnapshotNow"] = "Take snapshot now",
            ["Operations.LatestSnapshot"] = "Ultimo snapshot",
            ["Operations.OpenFolder"] = "Apri cartella",
            ["Operations.Analyze"] = "Analizza contesto corrente",
            ["Operations.Focus"] = "Sessione focus",
            ["Operations.Focus.Description"] = "Avvia, controlla o termina una sessione focus misurata.",
            ["Operations.FocusObjective.Header"] = "Obiettivo",
            ["Operations.FocusObjective.Placeholder"] = "Ad esempio: completare la revisione",
            ["Operations.Start"] = "Avvia",
            ["Operations.Status"] = "Stato",
            ["Operations.Stop"] = "Ferma",
            ["Operations.Summarize"] = "Genera un riepilogo alla chiusura",
            ["Operations.Reports"] = "Report e digest",
            ["Operations.Reports.Description"] = "Genera report locali dai dati correnti.",
            ["Operations.OpenGenerated"] = "Apri il report dopo la generazione",
            ["Operations.TodayReport"] = "Genera report di oggi",
            ["Operations.DigestDate.Header"] = "Data digest",
            ["Operations.DigestDate.Placeholder"] = "Seleziona una data",
            ["Operations.GenerateDigest"] = "Genera digest",
            ["Operations.Privacy"] = "Privacy",
            ["Operations.Privacy.Description"] = "Blocca processi, titoli finestra o indizi di contesto sensibili.",
            ["Operations.PrivacyType.Header"] = "Tipo regola",
            ["Operations.PrivacyType.process"] = "Processo",
            ["Operations.PrivacyType.title"] = "Titolo finestra",
            ["Operations.PrivacyType.hint"] = "Contesto",
            ["Operations.PrivacyValue.Header"] = "Valore",
            ["Operations.PrivacyValue.Placeholder"] = "Valore da bloccare",
            ["Operations.Add"] = "Aggiungi",
            ["Operations.Refresh"] = "Aggiorna",
            ["Operations.Remove"] = "Rimuovi selezionata",
            ["Operations.TestContext"] = "Test contesto",
            ["Operations.Retention"] = "Conservazione dati",
            ["Operations.Retention.Description"] = "Controlla la policy prima di una pulizia confermata.",
            ["Operations.Preview"] = "Anteprima",
            ["Operations.Run"] = "Esegui",
            ["Operations.Plugins"] = "Plugin di contesto",
            ["Operations.Plugins.Description"] = "Abilita o disabilita i provider di contesto supportati.",
            ["Operations.Enable"] = "Abilita",
            ["Operations.Disable"] = "Disabilita",
            ["Operations.Keep"] = "Conserva",
            ["Operations.Watermark"] = "Filigrana",
            ["Operations.AllowCapture"] = "Consenti un nuovo snapshot se necessario",
            ["Operations.Initial.Health"] = "Health non ancora acquisita.",
            ["Operations.Initial.SystemSnapshot"] = "Snapshot sistema non ancora acquisito.",
            ["Operations.Initial.Snapshot"] = "Nessuno snapshot acquisito.",
            ["Operations.Initial.Analysis"] = "Nessuna analisi eseguita.",
            ["Operations.Initial.Focus"] = "Nessuna sessione focus attiva.",
            ["Operations.Initial.Report"] = "Nessun report generato.",
            ["Operations.Initial.Retention"] = "Policy non ancora caricata.",
            ["Operations.Initial.RetentionPreview"] = "Anteprima non ancora calcolata.",
            ["About.Description"] = "Un player locale per comprendere tempo, applicazioni e ritmo di lavoro. Il contenuto digitato non viene mai registrato; snapshot e OpenAI sono sempre opt-in.",
            ["About.Close"] = "Chiudi",
            ["About.Version"] = "Versione",
            ["About.Built"] = "Compilata il",
            ["About.Machine"] = "Macchina di build",
            ["About.Commit"] = "Commit Git",
            ["About.Dirty"] = "modifiche non committate",
            ["Reports.Title"] = "Report",
            ["Reports.Motto"] = "Dai dati al ritmo.",
            ["Reports.Description"] = "Scopri quando lavori, su cosa e con quale continuità.",
            ["Reports.Range.Header"] = "Intervallo",
            ["Reports.Range.today"] = "Oggi",
            ["Reports.Range.7"] = "7 giorni",
            ["Reports.Range.30"] = "30 giorni",
            ["Reports.Range.90"] = "90 giorni",
            ["Reports.Range.thisMonth"] = "Questo mese",
            ["Reports.Range.lastMonth"] = "Mese scorso",
            ["Reports.Range.custom"] = "Personalizzato",
            ["Reports.View.Header"] = "Vista",
            ["Reports.View.calendar"] = "Calendario",
            ["Reports.View.hourOfWeek"] = "Fasce orarie",
            ["Reports.View.trend"] = "Andamento",
            ["Reports.View.applications"] = "Applicazioni",
            ["Reports.From.Header"] = "Dal",
            ["Reports.To.Header"] = "Al",
            ["Reports.Refresh"] = "Aggiorna"
        },
        ["fr"] = new()
        {
            ["StateRunning"] = "EN COURS",
            ["StatePaused"] = "EN PAUSE",
            ["StateIdleContext"] = "Inactif",
            ["StateReady"] = "Prêt à mesurer votre temps",
            ["NoSession"] = "Aucune session enregistrée",
            ["ApiKeyMissing"] = "Saisissez d'abord la clé API.",
            ["ApiKeySaved"] = "Clé enregistrée dans l'environnement utilisateur Windows. Non conservée par l'application.",
            ["ContextPlaceholder"] = "Prêt à mesurer votre temps",
            ["OptionsSaved"] = "Options enregistrées dans appsettings.json local.",
            ["ReportCreated"] = "Rapport créé",
            ["MenuTitleOptions"] = "Options",
            ["MenuTitleAbout"] = "À propos",
            ["MenuToggleOpenAi"] = "Intégration OpenAI",
            ["MenuToggleScreenshot"] = "Take snapshot now",
            ["TrackingNoticeRunning"] = "TrackMeUp est en cours...",
            ["TrackingNoticePaused"] = "TrackMeUp est en pause",
            ["ScreenshotDisabledHint"] = "Captures désactivées",
            ["LastSessionTitle"] = "DERNIÈRE SESSION",
            ["ActiveLabel"] = "ACTIF",
            ["KeysLabel"] = "TOUCHES",
            ["ClicksLabel"] = "CLICS"
        },
        ["de"] = new()
        {
            ["StateRunning"] = "IN ESECUZIONE",
            ["StatePaused"] = "IN PAUSA",
            ["StateIdleContext"] = "Inaktiv",
            ["StateReady"] = "Bereit, Ihre Zeit zu messen",
            ["NoSession"] = "Keine Sitzung aufgezeichnet",
            ["ApiKeyMissing"] = "Bitte zuerst den API-Schlüssel eingeben.",
            ["ApiKeySaved"] = "In die Windows-Benutzerumgebung gespeichert. Nicht in der App gespeichert.",
            ["ContextPlaceholder"] = "Bereit, Ihre Zeit zu messen",
            ["OptionsSaved"] = "Optionen in lokaler appsettings.json gespeichert.",
            ["ReportCreated"] = "Bericht erstellt",
            ["MenuTitleOptions"] = "App-Einstellungen",
            ["MenuTitleAbout"] = "Über",
            ["MenuToggleOpenAi"] = "OpenAI-Integration",
            ["MenuToggleScreenshot"] = "Take snapshot now",
            ["TrackingNoticeRunning"] = "TrackMeUp wird ausgeführt...",
            ["TrackingNoticePaused"] = "TrackMeUp ist pausiert",
            ["ScreenshotDisabledHint"] = "Screenshots deaktiviert",
            ["LastSessionTitle"] = "LETZTE SITZUNG",
            ["ActiveLabel"] = "AKTIV",
            ["KeysLabel"] = "TASTEN",
            ["ClicksLabel"] = "KLICKS"
        },
        ["es"] = new()
        {
            ["StateRunning"] = "EN CURSO",
            ["StatePaused"] = "PAUSADO",
            ["StateIdleContext"] = "Inactivo",
            ["StateReady"] = "Listo para medir tu tiempo",
            ["NoSession"] = "No hay sesión registrada",
            ["ApiKeyMissing"] = "Introduce primero una clave API.",
            ["ApiKeySaved"] = "Guardada en entorno de usuario de Windows. No se guarda en la app.",
            ["ContextPlaceholder"] = "Listo para medir tu tiempo",
            ["OptionsSaved"] = "Opciones guardadas en appsettings.json local.",
            ["ReportCreated"] = "Informe creado",
            ["MenuTitleOptions"] = "Opciones",
            ["MenuTitleAbout"] = "Acerca de",
            ["MenuToggleOpenAi"] = "Integración OpenAI",
            ["MenuToggleScreenshot"] = "Take snapshot now",
            ["TrackingNoticeRunning"] = "TrackMeUp se está ejecutando...",
            ["TrackingNoticePaused"] = "TrackMeUp está en pausa",
            ["ScreenshotDisabledHint"] = "Capturas desactivadas",
            ["LastSessionTitle"] = "ÚLTIMA SESIÓN",
            ["ActiveLabel"] = "ACTIVO",
            ["KeysLabel"] = "TECLAS",
            ["ClicksLabel"] = "CLICS"
        },
        ["vi"] = new()
        {
            ["StateRunning"] = "ĐANG THỰC HIỆN",
            ["StatePaused"] = "TẠM DỪNG",
            ["StateIdleContext"] = "Không hoạt động",
            ["StateReady"] = "Sẵn sàng đo thời gian của bạn",
            ["NoSession"] = "Không có phiên làm việc nào",
            ["ApiKeyMissing"] = "Nhập khóa API trước.",
            ["ApiKeySaved"] = "Lưu vào môi trường người dùng Windows. Không được lưu bởi ứng dụng.",
            ["ContextPlaceholder"] = "Sẵn sàng đo thời gian của bạn",
            ["OptionsSaved"] = "Đã lưu tùy chọn vào appsettings.json cục bộ.",
            ["ReportCreated"] = "Đã tạo báo cáo",
            ["MenuTitleOptions"] = "Tùy chọn",
            ["MenuTitleAbout"] = "Giới thiệu",
            ["MenuToggleOpenAi"] = "Tích hợp OpenAI",
            ["MenuToggleScreenshot"] = "Take snapshot now",
            ["TrackingNoticeRunning"] = "TrackMeUp đang chạy...",
            ["TrackingNoticePaused"] = "TrackMeUp đã tạm dừng",
            ["ScreenshotDisabledHint"] = "Ảnh chụp đã tắt",
            ["LastSessionTitle"] = "PHIÊN LÀM VIỆC CUỐI CÙNG",
            ["ActiveLabel"] = "HOẠT ĐỘNG",
            ["KeysLabel"] = "PHÍM",
            ["ClicksLabel"] = "BẤM"
        }
    };

    /// <summary>
    /// Selected language code.
    /// </summary>
    public string Language { get; }

    /// <summary>Gets the persisted language choice before system-language resolution.</summary>
    public string RequestedLanguage { get; }

    /// <summary>
    /// Creates service for supported language fallback to English.
    /// </summary>
    public LocalizationService(string language)
    {
        RequestedLanguage = string.IsNullOrWhiteSpace(language) ? "system" : language.Trim().ToLowerInvariant();
        Language = ResolveLanguage(RequestedLanguage, CultureInfo.CurrentUICulture);
    }

    /// <summary>Resolves a persisted override, using the Windows UI culture only for the system choice.</summary>
    public static string ResolveLanguage(string? requestedLanguage, CultureInfo systemCulture)
    {
        ArgumentNullException.ThrowIfNull(systemCulture);
        var requested = string.IsNullOrWhiteSpace(requestedLanguage) ? "system" : requestedLanguage.Trim().ToLowerInvariant();
        var resolved = requested == "system" ? systemCulture.TwoLetterISOLanguageName.ToLowerInvariant() : requested;
        return resolved is "en" or "it" or "vi" or "fr" or "de" or "es" ? resolved : "en";
    }

    /// <summary>
    /// Returns translated token text for given key.
    /// </summary>
    /// <param name="key">Resource key.</param>
    /// <returns>Localized value or fallback key.</returns>
    public string Translate(string key)
        => _dictionary.TryGetValue(Language, out var current) && current.TryGetValue(key, out var value)
            ? value
            : _dictionary["en"].TryGetValue(key, out var english)
                ? english
                : key;

    /// <summary>Tries the selected language and then the English product copy fallback.</summary>
    public bool TryTranslate(string key, out string value)
    {
        if (_dictionary.TryGetValue(Language, out var current) && current.TryGetValue(key, out value!))
        {
            return true;
        }

        return _dictionary["en"].TryGetValue(key, out value!);
    }
}
