export const reportLocales = [
  'en-US',
  'it-IT',
  'fr-FR',
  'de-DE',
  'es-ES',
  'zh-Hans',
  'vi-VN',
  'ko-KR',
  'pt-PT',
  'pt-BR',
] as const

export type ReportLocale = (typeof reportLocales)[number]

type TranslationRow = readonly [
  enUS: string,
  itIT: string,
  frFR: string,
  deDE: string,
  esES: string,
  zhHans: string,
  viVN: string,
  koKR: string,
  ptPT: string,
  ptBR: string,
]

// English text is the stable gettext-style message identifier. Keeping every locale in the
// same tuple makes omissions a type error and makes dialect differences directly reviewable.
const translationRows = [
  // Document, theme, navigation, loading, and errors.
  ['TrackMeUp Reports', 'Report TrackMeUp', 'Rapports TrackMeUp', 'TrackMeUp-Berichte', 'Informes de TrackMeUp', 'TrackMeUp 报告', 'Báo cáo TrackMeUp', 'TrackMeUp 보고서', 'Relatórios do TrackMeUp', 'Relatórios do TrackMeUp'],
  ['System', 'Sistema', 'Système', 'System', 'Sistema', '系统', 'Hệ thống', '시스템', 'Sistema', 'Sistema'],
  ['Light', 'Chiaro', 'Clair', 'Hell', 'Claro', '浅色', 'Sáng', '라이트', 'Claro', 'Claro'],
  ['Dark', 'Scuro', 'Sombre', 'Dunkel', 'Oscuro', '深色', 'Tối', '다크', 'Escuro', 'Escuro'],
  ['Daily activity', 'Attività giornaliera', 'Activité quotidienne', 'Tägliche Aktivität', 'Actividad diaria', '每日活动', 'Hoạt động hằng ngày', '일일 활동', 'Atividade diária', 'Atividade diária'],
  ['Compare days and quickly spot continuity, peaks and interruptions.', 'Confronta i giorni del periodo e individua rapidamente continuità, picchi e interruzioni.', 'Comparez les jours et repérez rapidement la continuité, les pics et les interruptions.', 'Vergleichen Sie Tage und erkennen Sie schnell Kontinuität, Spitzen und Unterbrechungen.', 'Compara los días y detecta rápidamente la continuidad, los picos y las interrupciones.', '比较各天，快速发现连续性、峰值和中断。', 'So sánh các ngày và nhanh chóng nhận ra tính liên tục, các đỉnh và gián đoạn.', '날짜별로 비교하여 연속성, 최고점 및 중단을 빠르게 확인하세요.', 'Compare os dias e identifique rapidamente a continuidade, os picos e as interrupções.', 'Compare os dias e identifique rapidamente a continuidade, os picos e as interrupções.'],
  ['Time bands', 'Fasce orarie', 'Plages horaires', 'Zeitfenster', 'Franjas horarias', '时间段', 'Khung giờ', '시간대', 'Faixas horárias', 'Faixas de horário'],
  ['See which hours and weekdays contain most of your active time.', 'Scopri in quali ore e giorni della settimana si concentra il tempo attivo.', 'Découvrez les heures et les jours de la semaine qui concentrent le plus de temps actif.', 'Sehen Sie, in welchen Stunden und Wochentagen der Großteil Ihrer aktiven Zeit liegt.', 'Consulta en qué horas y días de la semana se concentra la mayor parte del tiempo activo.', '查看活动时间主要集中在哪些时段和星期几。', 'Xem những giờ và ngày nào trong tuần có phần lớn thời gian hoạt động của bạn.', '활동 시간이 가장 많이 집중된 시간과 요일을 확인하세요.', 'Veja em que horas e dias da semana se concentra a maior parte do tempo ativo.', 'Veja em quais horários e dias da semana se concentra a maior parte do tempo ativo.'],
  ['Trend', 'Andamento', 'Tendance', 'Trend', 'Tendencia', '趋势', 'Xu hướng', '추세', 'Tendência', 'Tendência'],
  ['Follow the balance between detected activity and inactivity over time.', 'Segui nel tempo il rapporto fra attività rilevata e inattività.', 'Suivez au fil du temps l’équilibre entre l’activité détectée et l’inactivité.', 'Verfolgen Sie im Zeitverlauf das Verhältnis zwischen erkannter Aktivität und Inaktivität.', 'Sigue a lo largo del tiempo el equilibrio entre la actividad detectada y la inactividad.', '持续了解检测到的活动与空闲之间的平衡。', 'Theo dõi sự cân bằng giữa hoạt động được phát hiện và trạng thái không hoạt động theo thời gian.', '시간에 따른 감지된 활동과 비활동의 균형을 확인하세요.', 'Acompanhe ao longo do tempo o equilíbrio entre a atividade detetada e a inatividade.', 'Acompanhe ao longo do tempo o equilíbrio entre a atividade detectada e a inatividade.'],
  ['Applications', 'Applicazioni', 'Applications', 'Anwendungen', 'Aplicaciones', '应用程序', 'Ứng dụng', '애플리케이션', 'Aplicações', 'Aplicativos'],
  ['Compare the applications with the most active time in the period.', 'Confronta le applicazioni che hanno raccolto più tempo attivo nel periodo.', 'Comparez les applications ayant cumulé le plus de temps actif sur la période.', 'Vergleichen Sie die Anwendungen mit der höchsten aktiven Zeit im Zeitraum.', 'Compara las aplicaciones con más tiempo activo durante el periodo.', '比较所选期间活动时间最多的应用程序。', 'So sánh các ứng dụng có nhiều thời gian hoạt động nhất trong khoảng thời gian.', '기간 중 활동 시간이 가장 긴 애플리케이션을 비교하세요.', 'Compare as aplicações com mais tempo ativo no período.', 'Compare os aplicativos com mais tempo ativo no período.'],
  ['Search applications', 'Cerca applicazione', 'Rechercher des applications', 'Anwendungen suchen', 'Buscar aplicaciones', '搜索应用程序', 'Tìm kiếm ứng dụng', '애플리케이션 검색', 'Pesquisar aplicações', 'Pesquisar aplicativos'],
  ['Search the table', 'Cerca nella tabella', 'Rechercher dans le tableau', 'Tabelle durchsuchen', 'Buscar en la tabla', '搜索表格', 'Tìm kiếm trong bảng', '표 검색', 'Pesquisar na tabela', 'Pesquisar na tabela'],
  ['No results', 'Nessun risultato', 'Aucun résultat', 'Keine Ergebnisse', 'Sin resultados', '无结果', 'Không có kết quả', '결과 없음', 'Sem resultados', 'Nenhum resultado'],
  ['No data for this view', 'Nessun dato per questa vista', 'Aucune donnée pour cette vue', 'Keine Daten für diese Ansicht', 'No hay datos para esta vista', '此视图没有数据', 'Không có dữ liệu cho chế độ xem này', '이 보기에 데이터 없음', 'Sem dados para esta vista', 'Não há dados para esta visualização'],
  ['No items match your search. Change or clear the search text.', 'La ricerca non corrisponde ad alcun elemento. Modifica o cancella il testo cercato.', 'Aucun élément ne correspond à votre recherche. Modifiez ou effacez le texte recherché.', 'Keine Elemente entsprechen Ihrer Suche. Ändern oder löschen Sie den Suchtext.', 'Ningún elemento coincide con la búsqueda. Cambia o borra el texto de búsqueda.', '没有项目与搜索内容匹配。请更改或清除搜索文本。', 'Không có mục nào khớp với tìm kiếm. Hãy thay đổi hoặc xóa nội dung tìm kiếm.', '검색과 일치하는 항목이 없습니다. 검색어를 변경하거나 지우세요.', 'Nenhum item corresponde à pesquisa. Altere ou limpe o texto de pesquisa.', 'Nenhum item corresponde à pesquisa. Altere ou limpe o texto pesquisado.'],
  ['The selected period does not contain enough samples. Try a different range.', 'Il periodo selezionato non contiene campioni sufficienti. Prova un intervallo diverso.', 'La période sélectionnée ne contient pas assez d’échantillons. Essayez une autre plage.', 'Der ausgewählte Zeitraum enthält nicht genügend Stichproben. Wählen Sie einen anderen Bereich.', 'El periodo seleccionado no contiene suficientes muestras. Prueba otro intervalo.', '所选期间没有足够的样本。请尝试其他范围。', 'Khoảng thời gian đã chọn không có đủ mẫu. Hãy thử một phạm vi khác.', '선택한 기간에 충분한 샘플이 없습니다. 다른 범위를 사용해 보세요.', 'O período selecionado não contém amostras suficientes. Experimente outro intervalo.', 'O período selecionado não contém amostras suficientes. Tente outro intervalo.'],
  ['The requested theme preference is invalid.', 'La preferenza del tema richiesta non è valida.', 'La préférence de thème demandée n’est pas valide.', 'Die angeforderte Designeinstellung ist ungültig.', 'La preferencia de tema solicitada no es válida.', '请求的主题首选项无效。', 'Tùy chọn giao diện được yêu cầu không hợp lệ.', '요청한 테마 설정이 올바르지 않습니다.', 'A preferência de tema pedida é inválida.', 'A preferência de tema solicitada é inválida.'],
  ['The theme cannot be saved because the TrackMeUp connection is unavailable.', 'Il tema non può essere salvato perché il collegamento con TrackMeUp non è disponibile.', 'Le thème ne peut pas être enregistré, car la connexion à TrackMeUp est indisponible.', 'Das Design kann nicht gespeichert werden, da die Verbindung zu TrackMeUp nicht verfügbar ist.', 'El tema no se puede guardar porque la conexión con TrackMeUp no está disponible.', '由于无法连接 TrackMeUp，无法保存主题。', 'Không thể lưu giao diện vì kết nối TrackMeUp không khả dụng.', 'TrackMeUp 연결을 사용할 수 없어 테마를 저장할 수 없습니다.', 'Não é possível guardar o tema porque a ligação ao TrackMeUp não está disponível.', 'Não foi possível salvar o tema porque a conexão com o TrackMeUp não está disponível.'],
  ['TrackMeUp returned an invalid theme preference.', 'TrackMeUp ha restituito una preferenza del tema non valida.', 'TrackMeUp a renvoyé une préférence de thème non valide.', 'TrackMeUp hat eine ungültige Designeinstellung zurückgegeben.', 'TrackMeUp devolvió una preferencia de tema no válida.', 'TrackMeUp 返回了无效的主题首选项。', 'TrackMeUp đã trả về tùy chọn giao diện không hợp lệ.', 'TrackMeUp에서 올바르지 않은 테마 설정을 반환했습니다.', 'O TrackMeUp devolveu uma preferência de tema inválida.', 'O TrackMeUp retornou uma preferência de tema inválida.'],
  ['The theme preference was not saved{code}. The previous choice remains active.', 'La preferenza del tema non è stata salvata{code}. La scelta precedente resta attiva.', 'La préférence de thème n’a pas été enregistrée{code}. Le choix précédent reste actif.', 'Die Designeinstellung wurde nicht gespeichert{code}. Die vorherige Auswahl bleibt aktiv.', 'La preferencia de tema no se guardó{code}. La opción anterior sigue activa.', '未保存主题首选项{code}。之前的选择仍然有效。', 'Tùy chọn giao diện chưa được lưu{code}. Lựa chọn trước đó vẫn đang được áp dụng.', '테마 설정이 저장되지 않았습니다{code}. 이전 선택이 계속 적용됩니다.', 'A preferência de tema não foi guardada{code}. A escolha anterior permanece ativa.', 'A preferência de tema não foi salva{code}. A escolha anterior continua ativa.'],
  ['The received report is invalid.', 'Il report ricevuto non è valido.', 'Le rapport reçu n’est pas valide.', 'Der empfangene Bericht ist ungültig.', 'El informe recibido no es válido.', '收到的报告无效。', 'Báo cáo nhận được không hợp lệ.', '수신한 보고서가 올바르지 않습니다.', 'O relatório recebido é inválido.', 'O relatório recebido é inválido.'],
  ['The report is unavailable: TrackMeUp did not send a valid snapshot.', 'Il report non è disponibile: TrackMeUp non ha inviato uno snapshot valido.', 'Le rapport est indisponible : TrackMeUp n’a pas envoyé d’instantané valide.', 'Der Bericht ist nicht verfügbar: TrackMeUp hat keinen gültigen Snapshot gesendet.', 'El informe no está disponible: TrackMeUp no envió una instantánea válida.', '报告不可用：TrackMeUp 未发送有效快照。', 'Báo cáo không khả dụng: TrackMeUp chưa gửi bản chụp nhanh hợp lệ.', '보고서를 사용할 수 없습니다. TrackMeUp에서 올바른 스냅샷을 보내지 않았습니다.', 'O relatório não está disponível: o TrackMeUp não enviou um instantâneo válido.', 'O relatório não está disponível: o TrackMeUp não enviou um instantâneo válido.'],
  ['The report language sent by TrackMeUp is not supported.', 'La lingua del report inviata da TrackMeUp non è supportata.', 'La langue de rapport envoyée par TrackMeUp n’est pas prise en charge.', 'Die von TrackMeUp gesendete Berichtssprache wird nicht unterstützt.', 'El idioma del informe enviado por TrackMeUp no es compatible.', 'TrackMeUp 发送的报告语言不受支持。', 'Ngôn ngữ báo cáo do TrackMeUp gửi không được hỗ trợ.', 'TrackMeUp에서 보낸 보고서 언어는 지원되지 않습니다.', 'O idioma do relatório enviado pelo TrackMeUp não é suportado.', 'O idioma do relatório enviado pelo TrackMeUp não é compatível.'],
  ['Report tools', 'Strumenti del report', 'Outils du rapport', 'Berichtswerkzeuge', 'Herramientas del informe', '报告工具', 'Công cụ báo cáo', '보고서 도구', 'Ferramentas do relatório', 'Ferramentas do relatório'],
  ['Theme', 'Tema', 'Thème', 'Design', 'Tema', '主题', 'Giao diện', '테마', 'Tema', 'Tema'],
  ['Choose the report theme', 'Scegli il tema dei report', 'Choisir le thème du rapport', 'Berichtsdesign auswählen', 'Elegir el tema del informe', '选择报告主题', 'Chọn giao diện báo cáo', '보고서 테마 선택', 'Escolher o tema do relatório', 'Escolher o tema do relatório'],
  ['Loading report', 'Caricamento report', 'Chargement du rapport', 'Bericht wird geladen', 'Cargando informe', '正在加载报告', 'Đang tải báo cáo', '보고서 로드 중', 'A carregar relatório', 'Carregando relatório'],
  ['Preparing the report', 'Preparazione del report', 'Préparation du rapport', 'Bericht wird vorbereitet', 'Preparando el informe', '正在准备报告', 'Đang chuẩn bị báo cáo', '보고서 준비 중', 'A preparar o relatório', 'Preparando o relatório'],
  ['Waiting for data from TrackMeUp…', 'In attesa dei dati da TrackMeUp…', 'En attente des données de TrackMeUp…', 'Warten auf Daten von TrackMeUp…', 'Esperando datos de TrackMeUp…', '正在等待 TrackMeUp 数据…', 'Đang chờ dữ liệu từ TrackMeUp…', 'TrackMeUp 데이터 대기 중…', 'A aguardar dados do TrackMeUp…', 'Aguardando dados do TrackMeUp…'],
  ['Unable to display the report', 'Impossibile mostrare il report', 'Impossible d’afficher le rapport', 'Bericht kann nicht angezeigt werden', 'No se puede mostrar el informe', '无法显示报告', 'Không thể hiển thị báo cáo', '보고서를 표시할 수 없음', 'Não é possível apresentar o relatório', 'Não foi possível exibir o relatório'],

  // Shared report labels and accessible table copy.
  ['Date', 'Data', 'Date', 'Datum', 'Fecha', '日期', 'Ngày', '날짜', 'Data', 'Data'],
  ['Availability', 'Disponibilità', 'Disponibilité', 'Verfügbarkeit', 'Disponibilidad', '可用性', 'Tình trạng dữ liệu', '데이터 상태', 'Disponibilidade', 'Disponibilidade'],
  ['Activity score', 'Punteggio attività', 'Score d’activité', 'Aktivitätswert', 'Puntuación de actividad', '活动分数', 'Điểm hoạt động', '활동 점수', 'Pontuação de atividade', 'Pontuação de atividade'],
  ['Active', 'Attivo', 'Actif', 'Aktiv', 'Activo', '活动', 'Hoạt động', '활동', 'Ativo', 'Ativo'],
  ['Idle', 'Inattivo', 'Inactif', 'Inaktiv', 'Inactivo', '空闲', 'Không hoạt động', '비활동', 'Inativo', 'Inativo'],
  ['Tracked', 'Tracciato', 'Suivi', 'Erfasst', 'Registrado', '已跟踪', 'Đã theo dõi', '추적됨', 'Monitorizado', 'Monitorado'],
  ['Samples', 'Campioni', 'Échantillons', 'Stichproben', 'Muestras', '样本', 'Mẫu', '샘플', 'Amostras', 'Amostras'],
  ['Day', 'Giorno', 'Jour', 'Tag', 'Día', '天', 'Ngày', '요일', 'Dia', 'Dia'],
  ['Hour', 'Ora', 'Heure', 'Stunde', 'Hora', '小时', 'Giờ', '시간', 'Hora', 'Hora'],
  ['Average active', 'Attivo medio', 'Activité moyenne', 'Durchschnittlich aktiv', 'Actividad media', '平均活动', 'Hoạt động trung bình', '평균 활동', 'Atividade média', 'Atividade média'],
  ['Average idle', 'Inattivo medio', 'Inactivité moyenne', 'Durchschnittlich inaktiv', 'Inactividad media', '平均空闲', 'Không hoạt động trung bình', '평균 비활동', 'Inatividade média', 'Inatividade média'],
  ['Observed days', 'Giorni osservati', 'Jours observés', 'Beobachtete Tage', 'Días observados', '观测天数', 'Số ngày quan sát', '관찰된 일수', 'Dias observados', 'Dias observados'],
  ['Period', 'Periodo', 'Période', 'Zeitraum', 'Periodo', '期间', 'Khoảng thời gian', '기간', 'Período', 'Período'],
  ['Keys', 'Tasti', 'Touches', 'Tasten', 'Teclas', '按键', 'Phím', '키 입력', 'Teclas', 'Teclas'],
  ['Clicks', 'Clic', 'Clics', 'Klicks', 'Clics', '点击', 'Lượt nhấp', '클릭', 'Cliques', 'Cliques'],
  ['Application', 'Applicazione', 'Application', 'Anwendung', 'Aplicación', '应用程序', 'Ứng dụng', '애플리케이션', 'Aplicação', 'Aplicativo'],
  ['Active time', 'Tempo attivo', 'Temps actif', 'Aktive Zeit', 'Tiempo activo', '活动时间', 'Thời gian hoạt động', '활동 시간', 'Tempo ativo', 'Tempo ativo'],
  ['Data available', 'Dati presenti', 'Données disponibles', 'Daten verfügbar', 'Datos disponibles', '有数据', 'Có dữ liệu', '데이터 있음', 'Dados disponíveis', 'Dados disponíveis'],
  ['No data', 'Nessun dato', 'Aucune donnée', 'Keine Daten', 'Sin datos', '无数据', 'Không có dữ liệu', '데이터 없음', 'Sem dados', 'Sem dados'],
  ['Tabular data', 'Dati in formato tabellare', 'Données tabulaires', 'Tabellarische Daten', 'Datos tabulares', '表格数据', 'Dữ liệu dạng bảng', '표 형식 데이터', 'Dados em tabela', 'Dados em tabela'],
  ['Accessible alternative to the chart. Zero indicates a measured value; “No data” indicates an unobserved interval.', 'Alternativa accessibile al grafico. Lo zero indica un valore misurato; “Nessun dato” indica un intervallo non osservato.', 'Alternative accessible au graphique. Zéro indique une valeur mesurée ; « Aucune donnée » indique un intervalle non observé.', 'Barrierefreie Alternative zum Diagramm. Null steht für einen Messwert; „Keine Daten“ für ein nicht beobachtetes Intervall.', 'Alternativa accesible al gráfico. Cero indica un valor medido; «Sin datos» indica un intervalo no observado.', '图表的无障碍替代视图。零表示测量值；“无数据”表示未观测的时间段。', 'Phương án dạng bảng có thể truy cập thay cho biểu đồ. Số không biểu thị giá trị đã đo; “Không có dữ liệu” biểu thị khoảng chưa được quan sát.', '차트를 대신하는 접근성 표입니다. 0은 측정된 값을, “데이터 없음”은 관찰되지 않은 구간을 의미합니다.', 'Alternativa acessível ao gráfico. Zero indica um valor medido; «Sem dados» indica um intervalo não observado.', 'Alternativa acessível ao gráfico. Zero indica um valor medido; “Sem dados” indica um intervalo não observado.'],
  ['Report data in tabular format', 'Dati del report in formato tabellare', 'Données du rapport sous forme de tableau', 'Berichtsdaten in Tabellenform', 'Datos del informe en formato tabular', '表格形式的报告数据', 'Dữ liệu báo cáo ở dạng bảng', '표 형식의 보고서 데이터', 'Dados do relatório em formato de tabela', 'Dados do relatório em formato de tabela'],
  ['Unavailable', 'Non disponibile', 'Indisponible', 'Nicht verfügbar', 'No disponible', '不可用', 'Không khả dụng', '사용할 수 없음', 'Indisponível', 'Indisponível'],
  ['Data unavailable', 'Dato non disponibile', 'Données indisponibles', 'Daten nicht verfügbar', 'Datos no disponibles', '数据不可用', 'Dữ liệu không khả dụng', '데이터를 사용할 수 없음', 'Dados indisponíveis', 'Dados indisponíveis'],
  ['No data available', 'Nessun dato disponibile', 'Aucune donnée disponible', 'Keine Daten verfügbar', 'No hay datos disponibles', '没有可用数据', 'Không có dữ liệu khả dụng', '사용 가능한 데이터 없음', 'Não há dados disponíveis', 'Não há dados disponíveis'],
  ['hours', 'ore', 'heures', 'Stunden', 'horas', '小时', 'giờ', '시간', 'horas', 'horas'],
  ['Key indicators', 'Indicatori principali', 'Indicateurs clés', 'Kennzahlen', 'Indicadores clave', '关键指标', 'Chỉ số chính', '핵심 지표', 'Indicadores principais', 'Principais indicadores'],

  // AI usage, cost, and origin copy.
  ['No AI requests in the period', 'Nessuna richiesta AI nel periodo', 'Aucune requête d’IA sur la période', 'Keine KI-Anfragen im Zeitraum', 'No hay solicitudes de IA en el periodo', '此期间没有 AI 请求', 'Không có yêu cầu AI trong khoảng thời gian', '기간 중 AI 요청 없음', 'Sem pedidos de IA no período', 'Nenhuma solicitação de AI no período'],
  ['There are no AI requests to account for in the selected period.', 'Non ci sono richieste AI da contabilizzare nel periodo selezionato.', 'Aucune requête d’IA n’est à comptabiliser pour la période sélectionnée.', 'Im ausgewählten Zeitraum sind keine KI-Anfragen zu berücksichtigen.', 'No hay solicitudes de IA que contabilizar en el periodo seleccionado.', '所选期间没有需要统计的 AI 请求。', 'Không có yêu cầu AI nào cần tính trong khoảng thời gian đã chọn.', '선택한 기간에 집계할 AI 요청이 없습니다.', 'Não existem pedidos de IA a contabilizar no período selecionado.', 'Não há solicitações de AI para contabilizar no período selecionado.'],
  ['Estimated cost', 'Costo stimato', 'Coût estimé', 'Geschätzte Kosten', 'Coste estimado', '估算费用', 'Chi phí ước tính', '예상 비용', 'Custo estimado', 'Custo estimado'],
  ['No AI provider returned a per-request cost. The local pricing table estimates {estimated} of {total} requests.', 'Nessun provider AI ha restituito un costo per richiesta. Il listino locale stima {estimated} richieste su {total}.', 'Aucun fournisseur d’IA n’a renvoyé de coût par requête. Le barème local estime {estimated} requêtes sur {total}.', 'Kein KI-Anbieter hat Kosten pro Anfrage zurückgegeben. Die lokale Preistabelle schätzt {estimated} von {total} Anfragen.', 'Ningún proveedor de IA devolvió un coste por solicitud. La tabla de precios local estima {estimated} de {total} solicitudes.', '没有 AI 提供商返回单次请求费用。本地价格表估算了 {total} 个请求中的 {estimated} 个。', 'Không nhà cung cấp AI nào trả về chi phí cho từng yêu cầu. Bảng giá cục bộ ước tính {estimated} trong tổng số {total} yêu cầu.', '요청당 비용을 반환한 AI 제공업체가 없습니다. 로컬 가격표에서 총 {total}개 요청 중 {estimated}개를 추정합니다.', 'Nenhum fornecedor de IA devolveu um custo por pedido. A tabela de preços local estima {estimated} de {total} pedidos.', 'Nenhum fornecedor de IA retornou um custo por solicitação. A tabela de preços local estima {estimated} de {total} solicitações.'],
  ['Cost unavailable', 'Costo non disponibile', 'Coût indisponible', 'Kosten nicht verfügbar', 'Coste no disponible', '费用不可用', 'Chi phí không khả dụng', '비용을 사용할 수 없음', 'Custo indisponível', 'Custo indisponível'],
  ['No AI provider returned a per-request cost. Token counts remain available for usage analysis.', 'Nessun provider AI ha restituito un costo per richiesta. I conteggi dei token restano disponibili per l’analisi di utilizzo.', 'Aucun fournisseur d’IA n’a renvoyé de coût par requête. Le nombre de jetons reste disponible pour l’analyse de l’utilisation.', 'Kein KI-Anbieter hat Kosten pro Anfrage zurückgegeben. Die Tokenzahlen bleiben für die Nutzungsanalyse verfügbar.', 'Ningún proveedor de IA devolvió un coste por solicitud. Los recuentos de tokens siguen disponibles para analizar el uso.', '没有 AI 提供商返回单次请求费用。令牌计数仍可用于使用情况分析。', 'Không nhà cung cấp AI nào trả về chi phí cho từng yêu cầu. Số lượng token vẫn có thể dùng để phân tích mức sử dụng.', '요청당 비용을 반환한 AI 제공업체가 없습니다. 사용량 분석을 위한 토큰 수는 계속 제공됩니다.', 'Nenhum fornecedor de IA devolveu um custo por pedido. As contagens de tokens continuam disponíveis para análise de utilização.', 'Nenhum fornecedor de IA retornou um custo por solicitação. As contagens de tokens continuam disponíveis para análise de uso.'],
  ['Reported and estimated cost', 'Costo dichiarato e stimato', 'Coût déclaré et estimé', 'Gemeldete und geschätzte Kosten', 'Coste declarado y estimado', '报告费用和估算费用', 'Chi phí được báo cáo và ước tính', '보고 비용 및 예상 비용', 'Custo comunicado e estimado', 'Custo informado e estimado'],
  ['The AI provider reported {reported} costs, and the local pricing table estimated {estimated} requests.', 'Il provider AI ha dichiarato {reported} costi e il listino locale ha stimato {estimated} richieste.', 'Le fournisseur d’IA a déclaré {reported} coûts et le barème local a estimé {estimated} requêtes.', 'Der KI-Anbieter hat {reported} Kosten gemeldet und die lokale Preistabelle hat {estimated} Anfragen geschätzt.', 'El proveedor de IA declaró {reported} costes y la tabla de precios local estimó {estimated} solicitudes.', 'AI 提供商报告了 {reported} 笔费用，本地价格表估算了 {estimated} 个请求。', 'Nhà cung cấp AI đã báo cáo {reported} chi phí và bảng giá cục bộ đã ước tính {estimated} yêu cầu.', 'AI 제공업체가 {reported}건의 비용을 보고했으며 로컬 가격표에서 {estimated}개 요청을 추정했습니다.', 'O fornecedor de IA comunicou {reported} custos e a tabela de preços local estimou {estimated} pedidos.', 'O fornecedor de IA informou {reported} custos e a tabela de preços local estimou {estimated} solicitações.'],
  ['Partial cost', 'Costo parziale', 'Coût partiel', 'Teilkosten', 'Coste parcial', '部分费用', 'Chi phí một phần', '일부 비용', 'Custo parcial', 'Custo parcial'],
  ['The AI provider reported a cost for {reported} of {total} requests. The displayed total does not cover the other requests.', 'Il provider AI ha dichiarato il costo per {reported} richieste su {total}. Il totale mostrato non copre le altre richieste.', 'Le fournisseur d’IA a déclaré un coût pour {reported} requêtes sur {total}. Le total affiché ne couvre pas les autres requêtes.', 'Der KI-Anbieter hat Kosten für {reported} von {total} Anfragen gemeldet. Die angezeigte Summe deckt die übrigen Anfragen nicht ab.', 'El proveedor de IA declaró un coste para {reported} de {total} solicitudes. El total mostrado no incluye las demás solicitudes.', 'AI 提供商报告了 {total} 个请求中 {reported} 个的费用。显示的总额不包括其他请求。', 'Nhà cung cấp AI đã báo cáo chi phí cho {reported} trong tổng số {total} yêu cầu. Tổng hiển thị không bao gồm các yêu cầu còn lại.', 'AI 제공업체가 총 {total}개 요청 중 {reported}개의 비용을 보고했습니다. 표시된 합계에는 나머지 요청이 포함되지 않습니다.', 'O fornecedor de IA comunicou um custo para {reported} de {total} pedidos. O total apresentado não abrange os restantes pedidos.', 'O fornecedor de IA informou um custo para {reported} de {total} solicitações. O total exibido não inclui as demais solicitações.'],
  ['AI-provider-reported cost', 'Costo dichiarato dal provider AI', 'Coût déclaré par le fournisseur d’IA', 'Vom KI-Anbieter gemeldete Kosten', 'Coste declarado por el proveedor de IA', 'AI 提供商报告的费用', 'Chi phí do nhà cung cấp AI báo cáo', 'AI 제공업체 보고 비용', 'Custo comunicado pelo fornecedor de IA', 'Custo informado pelo fornecedor de IA'],
  ['The AI provider returned a cost for every AI request in the period.', 'Il provider AI ha restituito un costo per ogni richiesta AI del periodo.', 'Le fournisseur d’IA a renvoyé un coût pour chaque requête d’IA de la période.', 'Der KI-Anbieter hat für jede KI-Anfrage im Zeitraum Kosten zurückgegeben.', 'El proveedor de IA devolvió un coste para cada solicitud de IA del periodo.', 'AI 提供商返回了此期间每个 AI 请求的费用。', 'Nhà cung cấp AI đã trả về chi phí cho mọi yêu cầu AI trong khoảng thời gian.', 'AI 제공업체가 기간 내 모든 AI 요청의 비용을 반환했습니다.', 'O fornecedor de IA devolveu um custo para cada pedido de IA do período.', 'O fornecedor de IA retornou um custo para cada solicitação de IA no período.'],
  ['Requests', 'Richieste', 'Requêtes', 'Anfragen', 'Solicitudes', '请求', 'Yêu cầu', '요청', 'Pedidos', 'Solicitações'],
  ['{succeeded} succeeded, {failed} failed', '{succeeded} riuscite, {failed} non riuscite', '{succeeded} réussies, {failed} échouées', '{succeeded} erfolgreich, {failed} fehlgeschlagen', '{succeeded} correctas, {failed} fallidas', '{succeeded} 个成功，{failed} 个失败', '{succeeded} thành công, {failed} thất bại', '성공 {succeeded}개, 실패 {failed}개', '{succeeded} com êxito, {failed} falharam', '{succeeded} bem-sucedidas, {failed} com falha'],
  ['Input tokens', 'Token di input', 'Jetons d’entrée', 'Eingabe-Token', 'Tokens de entrada', '输入令牌', 'Token đầu vào', '입력 토큰', 'Tokens de entrada', 'Tokens de entrada'],
  ['Cached input: {count}', 'Input in cache: {count}', 'Entrée mise en cache : {count}', 'Zwischengespeicherte Eingabe: {count}', 'Entrada en caché: {count}', '缓存输入：{count}', 'Đầu vào được lưu đệm: {count}', '캐시된 입력: {count}', 'Entrada em cache: {count}', 'Entrada em cache: {count}'],
  ['Output tokens', 'Token di output', 'Jetons de sortie', 'Ausgabe-Token', 'Tokens de salida', '输出令牌', 'Token đầu ra', '출력 토큰', 'Tokens de saída', 'Tokens de saída'],
  ['Reasoning: {reasoning} · Thinking: {thinking}', 'Ragionamento: {reasoning} · Pensiero: {thinking}', 'Raisonnement : {reasoning} · Réflexion : {thinking}', 'Schlussfolgern: {reasoning} · Denken: {thinking}', 'Razonamiento: {reasoning} · Pensamiento: {thinking}', '推理：{reasoning} · 思考：{thinking}', 'Suy luận: {reasoning} · Suy nghĩ: {thinking}', '추론: {reasoning} · 사고: {thinking}', 'Raciocínio: {reasoning} · Pensamento: {thinking}', 'Raciocínio: {reasoning} · Pensamento: {thinking}'],
  ['Total tokens', 'Token totali', 'Total des jetons', 'Token insgesamt', 'Tokens totales', '令牌总数', 'Tổng số token', '총 토큰', 'Total de tokens', 'Total de tokens'],
  ['Input and output reported by the AI provider', 'Input e output riportati dal provider AI', 'Entrée et sortie déclarées par le fournisseur d’IA', 'Vom KI-Anbieter gemeldete Ein- und Ausgabe', 'Entrada y salida declaradas por el proveedor de IA', 'AI 提供商报告的输入和输出', 'Đầu vào và đầu ra do nhà cung cấp AI báo cáo', 'AI 제공업체가 보고한 입력 및 출력', 'Entrada e saída comunicadas pelo fornecedor de IA', 'Entrada e saída informadas pelo fornecedor de IA'],
  ['Reported cost', 'Costo dichiarato', 'Coût déclaré', 'Gemeldete Kosten', 'Coste declarado', '报告费用', 'Chi phí được báo cáo', '보고 비용', 'Custo comunicado', 'Custo informado'],
  ['{count} requests with cost', '{count} richieste con costo', '{count} requêtes avec un coût', '{count} Anfragen mit Kosten', '{count} solicitudes con coste', '{count} 个请求含费用', '{count} yêu cầu có chi phí', '비용이 있는 요청 {count}개', '{count} pedidos com custo', '{count} solicitações com custo'],
  ['{count} estimated requests', '{count} richieste stimate', '{count} requêtes estimées', '{count} geschätzte Anfragen', '{count} solicitudes estimadas', '{count} 个估算请求', '{count} yêu cầu ước tính', '예상 요청 {count}개', '{count} pedidos estimados', '{count} solicitações estimadas'],
  ['{count} estimated requests · Prices: {timestamp}', '{count} richieste stimate · Prezzi: {timestamp}', '{count} requêtes estimées · Tarifs : {timestamp}', '{count} geschätzte Anfragen · Preise: {timestamp}', '{count} solicitudes estimadas · Precios: {timestamp}', '{count} 个估算请求 · 价格更新时间：{timestamp}', '{count} yêu cầu ước tính · Giá: {timestamp}', '예상 요청 {count}개 · 가격: {timestamp}', '{count} pedidos estimados · Preços: {timestamp}', '{count} solicitações estimadas · Preços: {timestamp}'],
  ['AI telemetry', 'Telemetria AI', 'Télémétrie de l’IA', 'KI-Telemetrie', 'Telemetría de IA', 'AI 遥测', 'Dữ liệu đo lường AI', 'AI 원격 분석', 'Telemetria de IA', 'Telemetria de IA'],
  ['Token usage and costs', 'Utilizzo di token e costi', 'Utilisation des jetons et coûts', 'Token-Nutzung und Kosten', 'Uso de tokens y costes', '令牌使用量和费用', 'Mức sử dụng token và chi phí', '토큰 사용량 및 비용', 'Utilização de tokens e custos', 'Uso de tokens e custos'],
  ['Data collected for snapshot analysis. Costs use AI-provider-reported values when available and local pricing estimates otherwise.', 'Dati raccolti per le analisi degli snapshot. I costi usano i valori dichiarati dal provider AI quando disponibili e, negli altri casi, le stime del listino locale.', 'Données recueillies pour l’analyse des instantanés. Les coûts utilisent les valeurs déclarées par le fournisseur d’IA lorsqu’elles sont disponibles, sinon les estimations du barème local.', 'Für die Snapshot-Analyse erfasste Daten. Für Kosten werden, sofern verfügbar, die vom KI-Anbieter gemeldeten Werte verwendet, andernfalls lokale Preisschätzungen.', 'Datos recopilados para el análisis de instantáneas. Los costes usan los valores declarados por el proveedor de IA cuando están disponibles y, en caso contrario, las estimaciones de precios locales.', '为快照分析收集的数据。费用优先使用 AI 提供商报告的值，否则使用本地价格估算。', 'Dữ liệu được thu thập để phân tích bản chụp nhanh. Chi phí sử dụng giá trị do nhà cung cấp AI báo cáo khi có, nếu không sẽ dùng ước tính từ bảng giá cục bộ.', '스냅샷 분석을 위해 수집된 데이터입니다. 비용은 가능한 경우 AI 제공업체가 보고한 값을 사용하고, 그렇지 않으면 로컬 가격 추정치를 사용합니다.', 'Dados recolhidos para análise de instantâneos. Os custos utilizam os valores comunicados pelo fornecedor de IA quando disponíveis e, caso contrário, estimativas da tabela de preços local.', 'Dados coletados para análise de instantâneos. Os custos usam os valores informados pelo fornecedor de IA quando disponíveis e, caso contrário, estimativas da tabela de preços local.'],
  ['By AI provider', 'Per provider AI', 'Par fournisseur d’IA', 'Nach KI-Anbieter', 'Por proveedor de IA', '按 AI 提供商', 'Theo nhà cung cấp AI', 'AI 제공업체별', 'Por fornecedor de IA', 'Por fornecedor de IA'],
  ['AI usage broken down by provider', 'Utilizzo AI suddiviso per provider', 'Utilisation de l’IA ventilée par fournisseur', 'KI-Nutzung nach Anbieter', 'Uso de IA desglosado por proveedor', '按提供商细分的 AI 使用情况', 'Mức sử dụng AI theo nhà cung cấp', '제공업체별 AI 사용량', 'Utilização de IA discriminada por fornecedor', 'Uso de IA detalhado por fornecedor'],
  ['AI provider', 'Provider AI', 'Fournisseur d’IA', 'KI-Anbieter', 'Proveedor de IA', 'AI 提供商', 'Nhà cung cấp AI', 'AI 제공업체', 'Fornecedor de IA', 'Fornecedor de IA'],
  ['Input', 'Input', 'Entrée', 'Eingabe', 'Entrada', '输入', 'Đầu vào', '입력', 'Entrada', 'Entrada'],
  ['Output', 'Output', 'Sortie', 'Ausgabe', 'Salida', '输出', 'Đầu ra', '출력', 'Saída', 'Saída'],
  ['Total', 'Totale', 'Total', 'Gesamt', 'Total', '总计', 'Tổng', '합계', 'Total', 'Total'],
  ['Reported', 'Dichiarato', 'Déclaré', 'Gemeldet', 'Declarado', '已报告', 'Được báo cáo', '보고됨', 'Comunicado', 'Informado'],
  ['Estimated', 'Stimato', 'Estimé', 'Geschätzt', 'Estimado', '估算', 'Ước tính', '예상', 'Estimado', 'Estimado'],
  ['No AI-provider details available.', 'Nessun dettaglio sul provider AI disponibile.', 'Aucun détail sur le fournisseur d’IA n’est disponible.', 'Keine Details zum KI-Anbieter verfügbar.', 'No hay detalles disponibles del proveedor de IA.', '没有可用的 AI 提供商详细信息。', 'Không có thông tin chi tiết về nhà cung cấp AI.', '사용 가능한 AI 제공업체 세부 정보가 없습니다.', 'Não estão disponíveis detalhes do fornecedor de IA.', 'Não há detalhes disponíveis do fornecedor de IA.'],
  ['By origin', 'Per provenienza', 'Par origine', 'Nach Ursprung', 'Por origen', '按来源', 'Theo nguồn', '출처별', 'Por origem', 'Por origem'],
  ['AI usage broken down by request origin', 'Utilizzo AI suddiviso per provenienza della richiesta', 'Utilisation de l’IA ventilée par origine des requêtes', 'KI-Nutzung nach Anfrageursprung', 'Uso de IA desglosado por origen de la solicitud', '按请求来源细分的 AI 使用情况', 'Mức sử dụng AI theo nguồn yêu cầu', '요청 출처별 AI 사용량', 'Utilização de IA discriminada por origem do pedido', 'Uso de IA detalhado por origem da solicitação'],
  ['Origin', 'Provenienza', 'Origine', 'Ursprung', 'Origen', '来源', 'Nguồn', '출처', 'Origem', 'Origem'],
  ['No origin details available.', 'Nessun dettaglio sulla provenienza disponibile.', 'Aucun détail sur l’origine n’est disponible.', 'Keine Ursprungsdetails verfügbar.', 'No hay detalles disponibles del origen.', '没有可用的来源详细信息。', 'Không có thông tin chi tiết về nguồn.', '사용 가능한 출처 세부 정보가 없습니다.', 'Não estão disponíveis detalhes da origem.', 'Não há detalhes disponíveis da origem.'],
  ['WinUI operations', 'Operazioni WinUI', 'Opérations WinUI', 'WinUI-Vorgänge', 'Operaciones de WinUI', 'WinUI 操作', 'Thao tác WinUI', 'WinUI 작업', 'Operações WinUI', 'Operações do WinUI'],
  ['CLI AI', 'AI da CLI', 'IA de la CLI', 'CLI-KI', 'IA de la CLI', 'CLI AI', 'AI qua CLI', 'CLI AI', 'IA da CLI', 'IA da CLI'],
  ['Manual snapshot', 'Snapshot manuale', 'Instantané manuel', 'Manueller Snapshot', 'Instantánea manual', '手动快照', 'Bản chụp nhanh thủ công', '수동 스냅샷', 'Instantâneo manual', 'Instantâneo manual'],
  ['Scheduled snapshot', 'Snapshot pianificato', 'Instantané planifié', 'Geplanter Snapshot', 'Instantánea programada', '计划快照', 'Bản chụp nhanh theo lịch', '예약 스냅샷', 'Instantâneo agendado', 'Instantâneo agendado'],
  ['Reprocessed snapshot', 'Snapshot rielaborato', 'Instantané retraité', 'Neu verarbeiteter Snapshot', 'Instantánea reprocesada', '重新处理的快照', 'Bản chụp nhanh được xử lý lại', '재처리된 스냅샷', 'Instantâneo reprocessado', 'Instantâneo reprocessado'],
  ['Runtime AI', 'AI del runtime', 'IA du moteur d’exécution', 'Laufzeit-KI', 'IA del entorno de ejecución', '运行时 AI', 'AI thời gian chạy', '런타임 AI', 'IA do runtime', 'IA do runtime'],
  ['OCR refinement', 'Perfezionamento OCR', 'Affinage OCR', 'OCR-Verfeinerung', 'Mejora del OCR', 'OCR 优化', 'Tinh chỉnh OCR', 'OCR 보정', 'Aperfeiçoamento de OCR', 'Aprimoramento de OCR'],
  ['Manual', 'Manuale', 'Manuel', 'Manuell', 'Manual', '手动', 'Thủ công', '수동', 'Manual', 'Manual'],
  ['Unknown', 'Sconosciuta', 'Inconnu', 'Unbekannt', 'Desconocido', '未知', 'Không xác định', '알 수 없음', 'Desconhecido', 'Desconhecido'],

  // Charts, coverage, and KPI copy.
  ['Horizontal bar chart of applications with the most active time.', 'Grafico a barre orizzontali delle applicazioni con più tempo attivo.', 'Graphique à barres horizontales des applications ayant le plus de temps actif.', 'Horizontales Balkendiagramm der Anwendungen mit der höchsten aktiven Zeit.', 'Gráfico de barras horizontales de las aplicaciones con más tiempo activo.', '活动时间最多的应用程序横向条形图。', 'Biểu đồ thanh ngang về các ứng dụng có nhiều thời gian hoạt động nhất.', '활동 시간이 가장 긴 애플리케이션의 가로 막대 차트입니다.', 'Gráfico de barras horizontal das aplicações com mais tempo ativo.', 'Gráfico de barras horizontal dos aplicativos com mais tempo ativo.'],
  ['Top applications', 'Applicazioni principali', 'Principales applications', 'Top-Anwendungen', 'Aplicaciones principales', '热门应用程序', 'Ứng dụng hàng đầu', '상위 애플리케이션', 'Principais aplicações', 'Principais aplicativos'],
  ['Top twelve applications plus the remaining aggregate, ordered by active time.', 'Prime dodici applicazioni e aggregato delle altre, ordinati per tempo attivo.', 'Les douze principales applications et le total des autres, classés par temps actif.', 'Die zwölf wichtigsten Anwendungen sowie die zusammengefassten übrigen, sortiert nach aktiver Zeit.', 'Las doce aplicaciones principales más el conjunto de las demás, ordenadas por tiempo activo.', '按活动时间排序的前十二个应用程序及其余应用程序汇总。', 'Mười hai ứng dụng hàng đầu cùng phần tổng hợp còn lại, được sắp xếp theo thời gian hoạt động.', '활동 시간순으로 정렬된 상위 12개 애플리케이션과 나머지 합계입니다.', 'As doze principais aplicações e o agregado das restantes, ordenadas por tempo ativo.', 'Os doze principais aplicativos e o total dos demais, ordenados por tempo ativo.'],
  ['Applications ordered by active time', 'Applicazioni ordinate per tempo attivo', 'Applications classées par temps actif', 'Anwendungen nach aktiver Zeit sortiert', 'Aplicaciones ordenadas por tiempo activo', '按活动时间排序的应用程序', 'Ứng dụng được sắp xếp theo thời gian hoạt động', '활동 시간순 애플리케이션', 'Aplicações ordenadas por tempo ativo', 'Aplicativos ordenados por tempo ativo'],
  ['The chart is hidden in high contrast mode. Open the accessible table below to inspect all values.', 'Il grafico è nascosto in modalità contrasto elevato. Apri la tabella accessibile qui sotto per consultare tutti i valori.', 'Le graphique est masqué en mode contraste élevé. Ouvrez le tableau accessible ci-dessous pour consulter toutes les valeurs.', 'Das Diagramm ist im Modus mit hohem Kontrast ausgeblendet. Öffnen Sie die barrierefreie Tabelle darunter, um alle Werte anzuzeigen.', 'El gráfico está oculto en el modo de contraste alto. Abre la tabla accesible de abajo para consultar todos los valores.', '图表在高对比度模式下隐藏。请打开下方的无障碍表格以查看所有值。', 'Biểu đồ bị ẩn ở chế độ tương phản cao. Hãy mở bảng có thể truy cập bên dưới để xem tất cả giá trị.', '고대비 모드에서는 차트가 숨겨집니다. 모든 값을 확인하려면 아래의 접근성 표를 여세요.', 'O gráfico está oculto no modo de alto contraste. Abra a tabela acessível abaixo para consultar todos os valores.', 'O gráfico fica oculto no modo de alto contraste. Abra a tabela acessível abaixo para consultar todos os valores.'],
  ['Daily activity map. A stronger shade indicates more active time.', 'Mappa dell’attività giornaliera. Una tonalità più intensa indica più tempo attivo.', 'Carte de l’activité quotidienne. Une teinte plus soutenue indique davantage de temps actif.', 'Karte der täglichen Aktivität. Ein kräftigerer Farbton bedeutet mehr aktive Zeit.', 'Mapa de actividad diaria. Un tono más intenso indica más tiempo activo.', '每日活动图。颜色越深表示活动时间越长。', 'Bản đồ hoạt động hằng ngày. Màu đậm hơn biểu thị nhiều thời gian hoạt động hơn.', '일일 활동 지도입니다. 색상이 진할수록 활동 시간이 많음을 나타냅니다.', 'Mapa de atividade diária. Um tom mais intenso indica mais tempo ativo.', 'Mapa de atividade diária. Um tom mais forte indica mais tempo ativo.'],
  ['Coverage', 'Copertura', 'Couverture', 'Abdeckung', 'Cobertura', '覆盖率', 'Mức bao phủ', '범위', 'Cobertura', 'Cobertura'],
  ['More activity', 'Più attività', 'Plus d’activité', 'Mehr Aktivität', 'Más actividad', '活动较多', 'Hoạt động nhiều hơn', '활동 많음', 'Mais atividade', 'Mais atividade'],
  ['Less activity', 'Meno attività', 'Moins d’activité', 'Weniger Aktivität', 'Menos actividad', '活动较少', 'Hoạt động ít hơn', '활동 적음', 'Menos atividade', 'Menos atividade'],
  ['Activity calendar', 'Calendario dell’attività', 'Calendrier d’activité', 'Aktivitätskalender', 'Calendario de actividad', '活动日历', 'Lịch hoạt động', '활동 달력', 'Calendário de atividade', 'Calendário de atividades'],
  ['Active time by day; gray cells indicate missing data.', 'Tempo attivo per giorno; le celle grigie indicano assenza di dati.', 'Temps actif par jour ; les cellules grises indiquent des données manquantes.', 'Aktive Zeit nach Tag; graue Zellen kennzeichnen fehlende Daten.', 'Tiempo activo por día; las celdas grises indican datos ausentes.', '每日活动时间；灰色单元格表示缺少数据。', 'Thời gian hoạt động theo ngày; ô màu xám cho biết thiếu dữ liệu.', '날짜별 활동 시간이며 회색 셀은 누락된 데이터를 나타냅니다.', 'Tempo ativo por dia; as células cinzentas indicam dados em falta.', 'Tempo ativo por dia; as células cinza indicam dados ausentes.'],
  ['Legend: gray means no data', 'Legenda: il grigio indica nessun dato', 'Légende : le gris signifie aucune donnée', 'Legende: Grau bedeutet keine Daten', 'Leyenda: el gris significa que no hay datos', '图例：灰色表示无数据', 'Chú giải: màu xám nghĩa là không có dữ liệu', '범례: 회색은 데이터 없음을 의미', 'Legenda: cinzento significa sem dados', 'Legenda: cinza significa sem dados'],
  ['Active time map by day', 'Mappa del tempo attivo per giorno', 'Carte du temps actif par jour', 'Karte der aktiven Zeit nach Tag', 'Mapa de tiempo activo por día', '每日活动时间图', 'Bản đồ thời gian hoạt động theo ngày', '날짜별 활동 시간 지도', 'Mapa do tempo ativo por dia', 'Mapa do tempo ativo por dia'],
  ['Time coverage: {percent}', 'Copertura temporale: {percent}', 'Couverture temporelle : {percent}', 'Zeitabdeckung: {percent}', 'Cobertura temporal: {percent}', '时间覆盖率：{percent}', 'Mức bao phủ thời gian: {percent}', '시간 범위: {percent}', 'Cobertura temporal: {percent}', 'Cobertura de tempo: {percent}'],
  ['No data in the period', 'Nessun dato nel periodo', 'Aucune donnée sur la période', 'Keine Daten im Zeitraum', 'No hay datos en el periodo', '此期间无数据', 'Không có dữ liệu trong khoảng thời gian', '기간 내 데이터 없음', 'Sem dados no período', 'Não há dados no período'],
  ['TrackMeUp detected no samples in the selected range. Missing data is not counted as idle time.', 'TrackMeUp non ha rilevato campioni nell’intervallo selezionato. L’assenza di dati non viene conteggiata come inattività.', 'TrackMeUp n’a détecté aucun échantillon dans la plage sélectionnée. Les données manquantes ne sont pas comptées comme du temps inactif.', 'TrackMeUp hat im ausgewählten Bereich keine Stichproben erkannt. Fehlende Daten werden nicht als inaktive Zeit gezählt.', 'TrackMeUp no detectó muestras en el intervalo seleccionado. Los datos ausentes no se cuentan como tiempo inactivo.', 'TrackMeUp 在所选范围内未检测到样本。缺失数据不计为空闲时间。', 'TrackMeUp không phát hiện mẫu nào trong phạm vi đã chọn. Dữ liệu bị thiếu không được tính là thời gian không hoạt động.', 'TrackMeUp이 선택한 범위에서 샘플을 감지하지 못했습니다. 누락된 데이터는 비활동 시간으로 계산되지 않습니다.', 'O TrackMeUp não detetou amostras no intervalo selecionado. Os dados em falta não são contabilizados como tempo inativo.', 'O TrackMeUp não detectou amostras no intervalo selecionado. Os dados ausentes não são contabilizados como tempo inativo.'],
  ['Samples observed from {first} to {last}. Uncovered intervals are not interpreted as idle time.', 'Campioni osservati dal {first} al {last}. Gli intervalli non coperti non vengono interpretati come tempo inattivo.', 'Échantillons observés du {first} au {last}. Les intervalles non couverts ne sont pas interprétés comme du temps inactif.', 'Stichproben von {first} bis {last} beobachtet. Nicht abgedeckte Intervalle werden nicht als inaktive Zeit interpretiert.', 'Muestras observadas desde {first} hasta {last}. Los intervalos sin cobertura no se interpretan como tiempo inactivo.', '样本观测时间为 {first} 至 {last}。未覆盖的时间段不会被视为空闲时间。', 'Các mẫu được quan sát từ {first} đến {last}. Khoảng thời gian không được bao phủ không được coi là thời gian không hoạt động.', '{first}부터 {last}까지 샘플이 관찰되었습니다. 포함되지 않은 구간은 비활동 시간으로 해석되지 않습니다.', 'Amostras observadas de {first} a {last}. Os intervalos não abrangidos não são interpretados como tempo inativo.', 'Amostras observadas de {first} a {last}. Os intervalos não cobertos não são interpretados como tempo inativo.'],
  ['Average active-time map by weekday and hour.', 'Mappa del tempo attivo medio per giorno della settimana e fascia oraria.', 'Carte du temps actif moyen par jour de la semaine et par heure.', 'Karte der durchschnittlichen aktiven Zeit nach Wochentag und Stunde.', 'Mapa del tiempo activo medio por día de la semana y hora.', '按星期和小时显示的平均活动时间图。', 'Bản đồ thời gian hoạt động trung bình theo ngày trong tuần và giờ.', '요일 및 시간별 평균 활동 시간 지도입니다.', 'Mapa do tempo ativo médio por dia da semana e hora.', 'Mapa do tempo ativo médio por dia da semana e horário.'],
  ['Activity by day and hour', 'Attività per giorno e ora', 'Activité par jour et par heure', 'Aktivität nach Tag und Stunde', 'Actividad por día y hora', '按日期和小时显示活动', 'Hoạt động theo ngày và giờ', '요일 및 시간별 활동', 'Atividade por dia e hora', 'Atividade por dia e horário'],
  ['Average active time in the observed time bands.', 'Media del tempo attivo nelle fasce osservate del periodo.', 'Temps actif moyen dans les plages horaires observées.', 'Durchschnittliche aktive Zeit in den beobachteten Zeitfenstern.', 'Tiempo activo medio en las franjas horarias observadas.', '已观测时间段内的平均活动时间。', 'Thời gian hoạt động trung bình trong các khung giờ được quan sát.', '관찰된 시간대의 평균 활동 시간입니다.', 'Tempo ativo médio nas faixas horárias observadas.', 'Tempo ativo médio nas faixas de horário observadas.'],
  ['Average active-time map by weekday and hour', 'Mappa del tempo attivo medio per giorno della settimana e ora', 'Carte du temps actif moyen par jour de la semaine et par heure', 'Karte der durchschnittlichen aktiven Zeit nach Wochentag und Stunde', 'Mapa del tiempo activo medio por día de la semana y hora', '按星期和小时显示的平均活动时间图', 'Bản đồ thời gian hoạt động trung bình theo ngày trong tuần và giờ', '요일 및 시간별 평균 활동 시간 지도', 'Mapa do tempo ativo médio por dia da semana e hora', 'Mapa do tempo ativo médio por dia da semana e horário'],
  ['In the selected period', 'Nel periodo selezionato', 'Sur la période sélectionnée', 'Im ausgewählten Zeitraum', 'En el periodo seleccionado', '在所选期间', 'Trong khoảng thời gian đã chọn', '선택한 기간', 'No período selecionado', 'No período selecionado'],
  ['Idle time', 'Tempo inattivo', 'Temps inactif', 'Inaktive Zeit', 'Tiempo inactivo', '空闲时间', 'Thời gian không hoạt động', '비활동 시간', 'Tempo inativo', 'Tempo inativo'],
  ['While tracking', 'Durante il tracciamento', 'Pendant le suivi', 'Während der Erfassung', 'Durante el seguimiento', '跟踪期间', 'Trong khi theo dõi', '추적 중', 'Durante a monitorização', 'Durante o monitoramento'],
  ['Active days', 'Giorni attivi', 'Jours actifs', 'Aktive Tage', 'Días activos', '活动天数', 'Số ngày hoạt động', '활동 일수', 'Dias ativos', 'Dias ativos'],
  ['Days with activity', 'Giorni con attività', 'Jours avec activité', 'Tage mit Aktivität', 'Días con actividad', '有活动的天数', 'Ngày có hoạt động', '활동이 있는 날짜', 'Dias com atividade', 'Dias com atividade'],
  ['Daily average', 'Media giornaliera', 'Moyenne quotidienne', 'Tagesdurchschnitt', 'Media diaria', '每日平均值', 'Trung bình hằng ngày', '일일 평균', 'Média diária', 'Média diária'],
  ['Across active days', 'Sui giorni attivi', 'Sur les jours actifs', 'Über aktive Tage', 'En los días activos', '按活动天数计算', 'Trên các ngày hoạt động', '활동 일수 기준', 'Nos dias ativos', 'Nos dias ativos'],
  ['Top application', 'Applicazione principale', 'Principale application', 'Top-Anwendung', 'Aplicación principal', '首要应用程序', 'Ứng dụng hàng đầu', '상위 애플리케이션', 'Aplicação principal', 'Principal aplicativo'],
  ['{count} samples', '{count} campioni', '{count} échantillons', '{count} Stichproben', '{count} muestras', '{count} 个样本', '{count} mẫu', '샘플 {count}개', '{count} amostras', '{count} amostras'],
  ['Stacked bar chart of active and idle time by period.', 'Grafico a barre impilate del tempo attivo e inattivo per periodo.', 'Graphique à barres empilées du temps actif et inactif par période.', 'Gestapeltes Balkendiagramm der aktiven und inaktiven Zeit nach Zeitraum.', 'Gráfico de barras apiladas del tiempo activo e inactivo por periodo.', '按期间显示活动和空闲时间的堆叠条形图。', 'Biểu đồ thanh xếp chồng về thời gian hoạt động và không hoạt động theo khoảng thời gian.', '기간별 활동 및 비활동 시간의 누적 막대 차트입니다.', 'Gráfico de barras empilhadas do tempo ativo e inativo por período.', 'Gráfico de barras empilhadas do tempo ativo e inativo por período.'],
  ['No observed data', 'Nessun dato osservato', 'Aucune donnée observée', 'Keine beobachteten Daten', 'No hay datos observados', '无观测数据', 'Không có dữ liệu quan sát', '관찰된 데이터 없음', 'Sem dados observados', 'Não há dados observados'],
  ['Tracked time in the period', 'Tempo tracciato nel periodo', 'Temps suivi sur la période', 'Erfasste Zeit im Zeitraum', 'Tiempo registrado en el periodo', '期间内的跟踪时间', 'Thời gian được theo dõi trong khoảng', '기간 내 추적 시간', 'Tempo monitorizado no período', 'Tempo monitorado no período'],
  ['Active and idle time are stacked; intervals without data remain empty.', 'Attività e inattività sono impilate; gli intervalli senza dati restano vuoti.', 'Les temps actif et inactif sont empilés ; les intervalles sans données restent vides.', 'Aktive und inaktive Zeit werden gestapelt; Intervalle ohne Daten bleiben leer.', 'El tiempo activo e inactivo se apila; los intervalos sin datos quedan vacíos.', '活动和空闲时间会堆叠显示；没有数据的时间段保持为空。', 'Thời gian hoạt động và không hoạt động được xếp chồng; các khoảng không có dữ liệu được để trống.', '활동 및 비활동 시간이 누적되며 데이터가 없는 구간은 비어 있습니다.', 'O tempo ativo e inativo é empilhado; os intervalos sem dados permanecem vazios.', 'O tempo ativo e inativo é empilhado; os intervalos sem dados permanecem vazios.'],
  ['Active and idle time trend', 'Andamento del tempo attivo e inattivo', 'Tendance du temps actif et inactif', 'Trend der aktiven und inaktiven Zeit', 'Tendencia del tiempo activo e inactivo', '活动和空闲时间趋势', 'Xu hướng thời gian hoạt động và không hoạt động', '활동 및 비활동 시간 추세', 'Tendência do tempo ativo e inativo', 'Tendência do tempo ativo e inativo'],

  // Versioned report-envelope validation.
  ['The received message is not a TrackMeUp report.', 'Il messaggio ricevuto non è un report TrackMeUp.', 'Le message reçu n’est pas un rapport TrackMeUp.', 'Die empfangene Nachricht ist kein TrackMeUp-Bericht.', 'El mensaje recibido no es un informe de TrackMeUp.', '收到的消息不是 TrackMeUp 报告。', 'Thông báo nhận được không phải là báo cáo TrackMeUp.', '수신한 메시지가 TrackMeUp 보고서가 아닙니다.', 'A mensagem recebida não é um relatório do TrackMeUp.', 'A mensagem recebida não é um relatório do TrackMeUp.'],
  ['The requested view is not supported.', 'La vista richiesta non è supportata.', 'La vue demandée n’est pas prise en charge.', 'Die angeforderte Ansicht wird nicht unterstützt.', 'La vista solicitada no es compatible.', '不支持请求的视图。', 'Chế độ xem được yêu cầu không được hỗ trợ.', '요청한 보기는 지원되지 않습니다.', 'A vista pedida não é suportada.', 'A visualização solicitada não é compatível.'],
  ['The report does not contain a valid snapshot.', 'Il report non contiene uno snapshot valido.', 'Le rapport ne contient pas d’instantané valide.', 'Der Bericht enthält keinen gültigen Snapshot.', 'El informe no contiene una instantánea válida.', '报告不包含有效快照。', 'Báo cáo không chứa bản chụp nhanh hợp lệ.', '보고서에 올바른 스냅샷이 없습니다.', 'O relatório não contém um instantâneo válido.', 'O relatório não contém um instantâneo válido.'],
  ['The report version is not compatible with this application.', 'La versione del report non è compatibile con questa applicazione.', 'La version du rapport n’est pas compatible avec cette application.', 'Die Berichtsversion ist mit dieser Anwendung nicht kompatibel.', 'La versión del informe no es compatible con esta aplicación.', '报告版本与此应用程序不兼容。', 'Phiên bản báo cáo không tương thích với ứng dụng này.', '보고서 버전이 이 애플리케이션과 호환되지 않습니다.', 'A versão do relatório não é compatível com esta aplicação.', 'A versão do relatório não é compatível com este aplicativo.'],
  ['The report content is incomplete or invalid.', 'Il contenuto del report è incompleto o non valido.', 'Le contenu du rapport est incomplet ou non valide.', 'Der Berichtsinhalt ist unvollständig oder ungültig.', 'El contenido del informe está incompleto o no es válido.', '报告内容不完整或无效。', 'Nội dung báo cáo không đầy đủ hoặc không hợp lệ.', '보고서 내용이 불완전하거나 올바르지 않습니다.', 'O conteúdo do relatório está incompleto ou é inválido.', 'O conteúdo do relatório está incompleto ou é inválido.'],
] as const satisfies readonly TranslationRow[]

export type MessageKey = (typeof translationRows)[number][0]
export type MessageCatalog = Readonly<Record<MessageKey, string>>

const placeholderPattern = /\{([a-z][a-zA-Z0-9]*)\}/g

function placeholders(value: string): string[] {
  return [...value.matchAll(placeholderPattern)]
    .map((match) => match[1])
    .sort()
}

function assertTranslationRows(): void {
  const keys = new Set<string>()
  for (const row of translationRows) {
    if (keys.has(row[0])) throw new Error(`Duplicate report message key: ${row[0]}`)
    keys.add(row[0])

    const expectedPlaceholders = placeholders(row[0]).join('|')
    for (let index = 0; index < reportLocales.length; index++) {
      const value = row[index]
      if (value.trim().length === 0) {
        throw new Error(`Empty ${reportLocales[index]} report translation: ${row[0]}`)
      }

      if (placeholders(value).join('|') !== expectedPlaceholders) {
        throw new Error(`Placeholder mismatch in ${reportLocales[index]} report translation: ${row[0]}`)
      }
    }
  }
}

assertTranslationRows()

function buildCatalog(localeIndex: number): MessageCatalog {
  return Object.freeze(Object.fromEntries(
    translationRows.map((row) => [row[0], row[localeIndex]]),
  )) as MessageCatalog
}

export const reportCatalogs = Object.freeze(Object.fromEntries(
  reportLocales.map((locale, index) => [locale, buildCatalog(index)]),
)) as Readonly<Record<ReportLocale, MessageCatalog>>

export function isReportLocale(value: unknown): value is ReportLocale {
  return typeof value === 'string' && reportLocales.includes(value as ReportLocale)
}

export function messagePlaceholders(key: MessageKey): readonly string[] {
  return placeholders(key)
}
