name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Restore and audit NuGet dependencies
        shell: pwsh
        run: |
          Get-ChildItem -Recurse -Filter *.csproj | ForEach-Object {
            dotnet restore $_.FullName -p:NuGetAudit=true -p:NuGetAuditMode=all -p:NuGetAuditLevel=low -p:WarningsAsErrors=NU1901%3BNU1902%3BNU1903%3BNU1904
            if ($LASTEXITCODE -ne 0) {
              exit $LASTEXITCODE
            }
          }

      - name: Verify code formatting
        shell: pwsh
        run: |
          $env:Platform = 'x64'
          Get-ChildItem -Recurse -Filter *.csproj | ForEach-Object {
            dotnet format $_.FullName whitespace --verify-no-changes --no-restore
          }

      - name: Test with code analyzers
        shell: pwsh
        run: |
          Get-ChildItem -Recurse -Filter *.Tests.csproj | ForEach-Object {
            dotnet test $_.FullName -p:Platform=x64 --no-restore -p:EnforceCodeStyleInBuild=true -p:TreatWarningsAsErrors=true
          }

  build:
    name: build (${{ matrix.platform }})
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [x64, ARM64, x86]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Restore
        run: dotnet restore .\TrackMeUp\TrackMeUp.csproj

      - name: Build
        run: dotnet build .\TrackMeUp\TrackMeUp.csproj -p:Platform=${{ matrix.platform }} --no-restore
